<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>standard-10-old</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="standard-10-old_files/libs/clipboard/clipboard.min.js"></script>
<script src="standard-10-old_files/libs/quarto-html/quarto.js"></script>
<script src="standard-10-old_files/libs/quarto-html/popper.min.js"></script>
<script src="standard-10-old_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="standard-10-old_files/libs/quarto-html/anchor.min.js"></script>
<link href="standard-10-old_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="standard-10-old_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="standard-10-old_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="standard-10-old_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="standard-10-old_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<section id="foundations-trusts-and-grant-making-organizations" class="level1">
<h1>Foundations, Trusts, and Grant-Making Organizations</h1>
<p>This chapter covers foundation types. It explains three variables: FNDNCD (reason for 501(c)(3) status), SUBSECCD (subsection code), and FRCD (filing requirement code).</p>
<section id="c3-foundations" class="level2">
<h2 class="anchored" data-anchor-id="c3-foundations">501(c)(3) foundations</h2>
<p>To qualify as a 501(c)(3) private foundation, a foundation must exist to advance one of the following exempt purposes:</p>
<ul>
<li><p>Charitable, which includes:</p>
<ul>
<li><p>“Relief of the poor, the distressed, or the underprivileged;</p></li>
<li><p>Advancement of religion;</p></li>
<li><p>Advancement of education or science;</p></li>
<li><p>Erection or maintenance of public buildings, monuments, or works;</p></li>
<li><p>Lessening the burdens of government;</p></li>
<li><p>Lessening neighborhood tensions;</p></li>
<li><p>Eliminating prejudice and discrimination;</p></li>
<li><p>Defending human and civil rights secured by law; and</p></li>
<li><p>Combating community deterioration and juvenile delinquency.”</p></li>
</ul></li>
<li><p>Religious</p></li>
<li><p>Educational</p></li>
<li><p>Scientific</p></li>
<li><p>Literary</p></li>
<li><p>Testing for public safety</p></li>
<li><p>Fostering national or international amateur sports competition</p></li>
<li><p>Prevention of cruelty to children or animals<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p></li>
</ul>
<p>501(c)(3) foundations indicate which exempt purpose(s) they advance when they file Form 1023 or 1023-EZ to apply for recognition of exemption from federal income tax (aka “tax-exempt status”) <span class="citation" data-cites="irs-2014b irs-2020a">(<a href="#ref-irs-2014b" role="doc-biblioref">Service 2014</a>, <a href="#ref-irs-2020a" role="doc-biblioref">2020</a>)</span>.</p>
<p>501(c)(3) foundations are either public charities or private foundations.</p>
<section id="public-charities" class="level3">
<h3 class="anchored" data-anchor-id="public-charities">Public charities</h3>
<p>To qualify as a 501(c)(3) public charity, rather than a 501(c)(3) private foundation, an organization must be one of the following:</p>
<ul>
<li><p>A church, convention of churches, or association of churches</p></li>
<li><p>A school</p></li>
<li><p>A hospital or cooperative hospital service organization</p></li>
<li><p>A medical research organization operated in conjunction with a hospital</p></li>
<li><p>An organization operated for the benefit of a college or university that is owned or operated by a governmental unit</p></li>
<li><p>A federal, state, or local government or governmental unit</p></li>
<li><p>An organization that normally receives a substantial part of its support from a governmental unit or from the general public</p></li>
<li><p>A community trust</p></li>
<li><p>An agricultural research organization operated in conjunction with a land-grant college or university or a non-land-grant college of agriculture</p></li>
<li><p>An organization that normally receives more than 33 and 1/3% of its support from contributions, membership fees, and gross receipts from activities related to its exempt functions and receives no more than 33 and 1/3 percent of its support from gross investment income and unrelated business taxable income from businesses acquired by the organization after June 30, 1975</p></li>
<li><p>An organization organized and operated exclusively for testing for public safety</p></li>
<li><p>A 509(a)(3) supporting organization, including the following types:</p>
<ul>
<li><p>Type I – those operated, supervised, or controlled by the supported organization(s) by giving the supported organization(s) the power to regularly appoint or elect a majority of the directors or trustees of the supporting organization</p></li>
<li><p>Type II – those supervised or controlled in connection with the supported organization(s) by having control or management of the supporting organization vested in the same persons that control or manage the supported organization(s)</p></li>
<li><p>Type III functionally integrated – those operated in connection with, and functionally integrated with, the supported organization(s)</p></li>
<li><p>Type III non-functionally integrated – those operated in connection with the supported organization(s) that are not functionally integrated <span class="citation" data-cites="irs-2022f">(<a href="#ref-irs-2022f" role="doc-biblioref">Service 2022</a>)</span></p></li>
</ul></li>
</ul>
<p>501(c)(3) organizations indicate whether they are a public charity or a private foundation when they file Form 1023 or 1023-EZ, and if they are a public charity, they must select the reason they are not a private foundation <span class="citation" data-cites="irs-2014b irs-2020a">(<a href="#ref-irs-2014b" role="doc-biblioref">Service 2014</a>, <a href="#ref-irs-2020a" role="doc-biblioref">2020</a>)</span>. 501(c)(3) public charities also select the reason they are not a private foundation when they file Schedule A (Form 990) every year <span class="citation" data-cites="irs-2022f">(<a href="#ref-irs-2022f" role="doc-biblioref">Service 2022</a>)</span>. Private foundations that later want to be reclassified as public charities must terminate their private foundation status and apply for public charity status.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Most 501(c)(3) foundations that qualify for public charity status must file an annual Form 990-N, 990-EZ, or 990.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
</section>
<section id="private-foundations" class="level3">
<h3 class="anchored" data-anchor-id="private-foundations">Private foundations</h3>
<p>The IRS distinguishes between 3 types of 501(c)(3) private foundations:</p>
<ol type="1">
<li><strong>Private operating foundations</strong> use most of their resources to actively conduct their exempt activities.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></li>
<li><strong>Exempt operating foundations</strong> are private operating foundations that have been publicly supported for at least 10 years, have governing bodies with less than 25% disqualified individuals and that broadly represent the general public, and have no disqualified individuals as officers.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> “Disqualified individuals” in this case refers to substantial contributors to the foundation; owners of more than 20% of the total combined voting power of a corporation, the profits interest of a partnership, or the beneficial interest of a trust or unincorporated enterprise (if these entities are substantial contributors to the foundation); and family members of any individuals previously described.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></li>
<li><strong>Grant-making (private nonoperating) foundations</strong> are all other private foundations.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></li>
</ol>
<p>501(c)(3) private foundations indicate whether they are a private operating foundation when they file Form 1023 <span class="citation" data-cites="irs-2020a">(<a href="#ref-irs-2020a" role="doc-biblioref">Service 2020</a>)</span>. This option is not available to Form 1023-EZ filers <span class="citation" data-cites="irs-2014b">(<a href="#ref-irs-2014b" role="doc-biblioref">Service 2014</a>)</span>. Later, private operating foundations that want recognition of exempt private operating foundation status must file Form 8940, Request for Miscellaneous Determination, to obtain a determination letter.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<p>Private foundations must file an annual Form 990-PF.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></p>
</section>
<section id="advantages-of-private-operating-foundations-and-exempt-operating-foundations-over-grant-making-private-nonoperating-foundations" class="level3">
<h3 class="anchored" data-anchor-id="advantages-of-private-operating-foundations-and-exempt-operating-foundations-over-grant-making-private-nonoperating-foundations">Advantages of private operating foundations and exempt operating foundations over grant-making (private nonoperating) foundations</h3>
<p>Private operating foundations have the following advantages over grant-making (private nonoperating) foundations:</p>
<ul>
<li>They are exempt from the excise tax on failure to distribute income.</li>
<li>Donors can deduct contributions to these foundations to the extent of 50% of their adjusted gross income, instead of 30%.</li>
<li>Private foundations can make qualifying distributions to them, as long as they are not controlled by said private foundation.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></li>
</ul>
<p>In addition, <em>exempt</em> operating foundations have the following advantages over grant-making (private nonoperating) foundations:</p>
<ul>
<li>They are exempt from taxes on net investment income.</li>
<li>Private foundations can make grants to them without following expenditure responsibility requirements.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></li>
</ul>
</section>
<section id="advantages-of-public-charities-over-private-foundations" class="level3">
<h3 class="anchored" data-anchor-id="advantages-of-public-charities-over-private-foundations">Advantages of public charities over private foundations</h3>
<p>The IRS imposes several taxes, restrictions, and requirements on private foundations that it does not place on public charities:</p>
<ul>
<li><p>Private foundations must pay excise taxes on their net investment income.</p></li>
<li><p>Private foundations must pay excise taxes on acts of self-dealing with disqualified individuals.</p></li>
<li><p>Private foundations must distribute a portion of their income annually for charitable purposes.</p></li>
<li><p>Private foundations must pay excise taxes on any excess holdings above 20% that it and all of its disqualified individuals have in the voting stock of a business enterprise.</p></li>
<li><p>Private foundations must pay excise taxes on jeopardizing investments (i.e., those that jeopardize the carrying out of exempt purposes).</p></li>
<li><p>Private foundations must pay excise taxes on expenditures that do not further exempt purposes, such as lobbying.<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></p></li>
</ul>
</section>
</section>
<section id="c17-trusts-providing-for-the-payment-of-supplemental-unemployment-compensation-benefits" class="level2">
<h2 class="anchored" data-anchor-id="c17-trusts-providing-for-the-payment-of-supplemental-unemployment-compensation-benefits">501(c)(17) trusts providing for the payment of supplemental unemployment compensation benefits</h2>
<p>An organization must meet the following requirements for to qualify for exemption from federal income tax as a 501(c)(17) trust providing for the payment of supplemental unemployment compensation benefits:</p>
<ol type="1">
<li><p>“The trust must constitute a valid trust under local law, be evidenced by an executed written document, and be part of a written plan.</p></li>
<li><p>The plan must be established and maintained by an employer or its employees solely for the purpose of providing supplemental unemployment compensation benefits.</p></li>
<li><p>The plan must provide that the corpus and income of the trust cannot be used for, or diverted to, any purpose other than providing such benefits prior to the satisfaction of all liabilities to the employees covered by the plan.</p></li>
<li><p>Benefits must be determined according to objective standards, and may not be determined solely in the discretion of the trustees.</p></li>
<li><p>The eligibility requirements and the benefits payable must not discriminate in favor of officers, shareholders, supervisory employees, or highly compensated employees.&nbsp; Benefits payable under the plan will not be considered discriminatory if they bear a uniform relationship to the total compensation of the employees covered by the plan.”<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a></p></li>
</ol>
<p>These trusts apply for recognition of exemption from federal income tax by filing Form 1024.<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a> They must file an annual Form 990-N, 990-EZ, or 990 <span class="citation" data-cites="irs-2023c">(<a href="#ref-irs-2023c" role="doc-biblioref">Service 2023</a>)</span>.</p>
</section>
<section id="c18-employee-funded-pension-trusts" class="level2">
<h2 class="anchored" data-anchor-id="c18-employee-funded-pension-trusts">501(c)(18) employee funded pension trusts</h2>
<p>501(c)(18) employee funded pension trusts pay benefits under pension plans that employees fund <span class="citation" data-cites="irs-2023c">(<a href="#ref-irs-2023c" role="doc-biblioref">Service 2023</a>)</span>. These trusts apply for recognition of exemption from federal income tax by filing Form 1024.<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a> They must file an annual Form 990-N, 990-EZ, or 990 <span class="citation" data-cites="irs-2023c">(<a href="#ref-irs-2023c" role="doc-biblioref">Service 2023</a>)</span>.</p>
</section>
<section id="c21-black-lung-benefit-trusts" class="level2">
<h2 class="anchored" data-anchor-id="c21-black-lung-benefit-trusts">501(c)(21) black lung benefit trusts</h2>
<p>Coal mine operators fund 501(c)(21) black lung benefit trusts “to satisfy their liability for disability or death due to black lung diseases” <span class="citation" data-cites="irs-2023c">(<a href="#ref-irs-2023c" role="doc-biblioref">Service 2023, 69</a>)</span>. These trusts apply for recognition of exemption from federal income tax by filing Form 1024.<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a> They must file an annual Form 990 <span class="citation" data-cites="irs-2023c">(<a href="#ref-irs-2023c" role="doc-biblioref">Service 2023</a>)</span>.</p>
</section>
<section id="a1-charitable-trusts" class="level2">
<h2 class="anchored" data-anchor-id="a1-charitable-trusts">4947(a)(1) charitable trusts</h2>
<p>A 4947(a)(1) charitable trusts is “a trust that is not tax exempt, all of the unexpired interests of which are devoted to one or more charitable purposes, and for which a charitable contribution deduction was allowed under a specific section of the Internal Revenue Code.”<a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a></p>
<p>The IRS treats them as private foundations unless they meet one of the requirements for being a public charity.<a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a></p>
<p>4947(a)(1) charitable trusts not treated as private foundations must file an annual Form 990-EZ or 990.<a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a> 4947(a)(1) charitable trusts treated as private foundations must file an annual Form 990-PF.<a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a></p>
</section>
<section id="a2-split-interest-charitable-trusts" class="level2">
<h2 class="anchored" data-anchor-id="a2-split-interest-charitable-trusts">4947(a)(2) split-interest charitable trusts</h2>
<p>4947(a)(2) split-interest charitable trusts “make distributions to both charitable and noncharitable beneficiaries, while providing tax benefits to their donor.”<a href="#fn21" class="footnote-ref" id="fnref21" role="doc-noteref"><sup>21</sup></a> They are not exempt from federal income tax.<a href="#fn22" class="footnote-ref" id="fnref22" role="doc-noteref"><sup>22</sup></a></p>
<p>4947(a)(2) split-interest charitable trusts must file an annual Form 5227: Split-Interest Trust Information Return.<a href="#fn23" class="footnote-ref" id="fnref23" role="doc-noteref"><sup>23</sup></a></p>
</section>
<section id="fndncd---reason-for-501c3-status" class="level2">
<h2 class="anchored" data-anchor-id="fndncd---reason-for-501c3-status">FNDNCD - reason for 501(c)(3) status</h2>
<table class="table">
<colgroup>
<col style="width: 1%">
<col style="width: 18%">
<col style="width: 79%">
</colgroup>
<thead>
<tr class="header">
<th>Value</th>
<th>Description</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>00</td>
<td>All organizations except 501(c)(3)</td>
<td>Organizations that are not 501(c)(3) public charities or private foundations</td>
</tr>
<tr class="even">
<td>02</td>
<td>Private operating foundation exempt from paying excise taxes on investment income</td>
<td>501(c)(3) private foundations: exempt operating foundations</td>
</tr>
<tr class="odd">
<td>03</td>
<td>Private operating foundation (other)</td>
<td>501(c)(3) private foundations: private operating foundations</td>
</tr>
<tr class="even">
<td>04</td>
<td>Private non-operating foundation</td>
<td>501(c)(3) private foundations: grant-making (private nonoperating) foundations</td>
</tr>
<tr class="odd">
<td>09</td>
<td>Suspense</td>
<td>???</td>
</tr>
<tr class="even">
<td>10</td>
<td>Church</td>
<td>501(c)(3) public charities: They qualify as public charities because they are a church, convention of churches, or association of churches.</td>
</tr>
<tr class="odd">
<td>11</td>
<td>School</td>
<td>501(c)(3) public charities: They qualify as public charities because they are a school.</td>
</tr>
<tr class="even">
<td>12</td>
<td>Hospital or medical research organization</td>
<td>501(c)(3) public charities: They qualify as public charities because they are a hospital, cooperative hospital service organization, or a medical research organization operated in conjunction with a hospital.</td>
</tr>
<tr class="odd">
<td>13</td>
<td>Organization operated for the benefit of a public (government owned or run) college or university</td>
<td>501(c)(3) public charities: They qualify as public charities because they are operated for the benefit of a college or university that is owned or operated by a governmental unit.</td>
</tr>
<tr class="even">
<td>14</td>
<td>Governmental unit</td>
<td>501(c)(3) public charities: They qualify as public charities because they are a federal, state, or local government or governmental unit.</td>
</tr>
<tr class="odd">
<td>15</td>
<td>Organization with a substantial portion of support from a governmental unit or the general public</td>
<td>501(c)(3) public charities: They qualify as public charities because they normally receive a substantial part of their support from a governmental unit or from the general public.</td>
</tr>
<tr class="even">
<td>16</td>
<td>Org income is &lt;=1/3 investment or unrelated business and &gt;1/3 donated or related to purpose</td>
<td>501(c)(3) public charities: They qualify as public charities because they normally receive more than 33 and 1/3% of their support from contributions, membership fees, and gross receipts from activities related to their exempt functions and receives no more than 33 and 1/3 percent of their support from gross investment income and unrelated business taxable income from businesses acquired by the organization after June 30, 1975.</td>
</tr>
<tr class="odd">
<td>17</td>
<td>Supporting Organization 509(a)(3) for benefit and in conjunction with organization(s) coded 10-16</td>
<td>???</td>
</tr>
<tr class="even">
<td>18</td>
<td>Organization organized and operated to test for public safety</td>
<td>501(c)(3) public charities: They qualify as public charities because they are organized and operated exclusively for testing for public safety.</td>
</tr>
<tr class="odd">
<td>21</td>
<td>Supporting Organization 509(a)(3) Type I</td>
<td>501(c)(3) public charities: They qualify as public charities because they are type I 509(a)(3) supporting organizations – those operated, supervised, or controlled by the supported organization(s) by giving the supported organization(s) the power to regularly appoint or elect a majority of the directors or trustees of the supporting organization.</td>
</tr>
<tr class="even">
<td>22</td>
<td>Supporting Organization 509(a)(3) Type II</td>
<td>501(c)(3) public charities: They qualify as public charities because they are type II 509(a)(3) supporting organizations – those supervised or controlled in connection with the supported organization(s) by having control or management of the supporting organization vested in the same persons that control or manage the supported organization(s).</td>
</tr>
<tr class="odd">
<td>23</td>
<td>Supporting Organization 509(a)(3) Type III functionally integrated</td>
<td>501(c)(3) public charities: They qualify as public charities because they are type III functionally integrated 509(a)(3) supporting organizations – those operated in connection with, and functionally integrated with, the supported organization(s).</td>
</tr>
<tr class="even">
<td>24</td>
<td>Supporting Organization 509(a)(3) Type III not functionally integrated</td>
<td>501(c)(3) public charities: They qualify as public charities because they are type III not functionally integrated 509(a)(3) supporting organizations – those operated in connection with the supported organization(s) that are not functionally integrated.</td>
</tr>
</tbody>
</table>
</section>
<section id="subseccd---subsection-code" class="level2">
<h2 class="anchored" data-anchor-id="subseccd---subsection-code">SUBSECCD - subsection code</h2>
<table class="table">
<colgroup>
<col style="width: 9%">
<col style="width: 90%">
</colgroup>
<thead>
<tr class="header">
<th>501(c) Status</th>
<th>Type of Organization</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>501(c)(1)</td>
<td>Corporations organized under acts of Congress</td>
</tr>
<tr class="even">
<td>501(c)(2)</td>
<td>Title holding corporations</td>
</tr>
<tr class="odd">
<td>501(c)(3)</td>
<td>Public charities and private foundations</td>
</tr>
<tr class="even">
<td>501(c)(4)</td>
<td>Civic leagues, social welfare organizations, and local associations of employees</td>
</tr>
<tr class="odd">
<td>501(c)(5)</td>
<td>Labor, agricultural, or horticultural organizations</td>
</tr>
<tr class="even">
<td>501(c)(6)</td>
<td>Business leagues, chambers of commerce, etc.</td>
</tr>
<tr class="odd">
<td>501(c)(7)</td>
<td>Social clubs</td>
</tr>
<tr class="even">
<td>501(c)(8)</td>
<td>Fraternal beneficiary societies, etc., providing life, sick, accident, or other benefits to members</td>
</tr>
<tr class="odd">
<td>501(c)(9)</td>
<td>Voluntary employees’ beneficiary associations</td>
</tr>
<tr class="even">
<td>501(c)(10)</td>
<td>Domestic fraternal societies, orders, etc., not providing life, sick, accident, or other benefits</td>
</tr>
<tr class="odd">
<td>501(c)(11)</td>
<td>Teachers’ retirement fund associations</td>
</tr>
<tr class="even">
<td>501(c)(12)</td>
<td>Benevolent life insurance associations, mutual ditch or irrigation companies, mutual or cooperative telephone companies, or like organizations</td>
</tr>
<tr class="odd">
<td>501(c)(13)</td>
<td>Cemeteries, crematoria, and like corporations</td>
</tr>
<tr class="even">
<td>501(c)(14)</td>
<td>Credit unions</td>
</tr>
<tr class="odd">
<td>501(c)(15)</td>
<td>Mutual insurance companies or associations, other than life or marine</td>
</tr>
<tr class="even">
<td>501(c)(16)</td>
<td>Corporations organized to finance crop operations</td>
</tr>
<tr class="odd">
<td>501(c)(17)</td>
<td>Trusts providing for the payment of supplemental unemployment compensation benefits</td>
</tr>
<tr class="even">
<td>501(c)(18)</td>
<td>Employee funded pension trusts</td>
</tr>
<tr class="odd">
<td>501(c)(19)</td>
<td>A post, organization, auxiliary unit, etc., of past or present members of the Armed Forces of the United States</td>
</tr>
<tr class="even">
<td>501(c)(20)</td>
<td><p>Qualified group legal services plans</p>
<p>Note: Section 501(c)(20) was terminated for taxable years beginning after June 30, 1992.<a href="#fn24" class="footnote-ref" id="fnref24" role="doc-noteref"><sup>24</sup></a></p></td>
</tr>
<tr class="odd">
<td>501(c)(21)</td>
<td>Black lung benefit trusts</td>
</tr>
<tr class="even">
<td>501(c)(22)</td>
<td>Withdrawal liability payment funds</td>
</tr>
<tr class="odd">
<td>501(c)(23)</td>
<td>Veterans’ organizations (created before 1880)</td>
</tr>
<tr class="even">
<td>501(c)(24)</td>
<td><p>Trusts described in section 4049 of the Employee Retirement Income Security Act (ERISA) of 1974</p>
<p>Note: The Omnibus Budget Reconciliation Act of 1987 repealed section 4049 of ERISA.<a href="#fn25" class="footnote-ref" id="fnref25" role="doc-noteref"><sup>25</sup></a></p></td>
</tr>
<tr class="odd">
<td>501(c)(25)</td>
<td>Title holding corporations or trusts with multiple parents</td>
</tr>
<tr class="even">
<td>501(c)(26)</td>
<td>State-sponsored high-risk health coverage organizations</td>
</tr>
<tr class="odd">
<td>501(c)(27)</td>
<td>State-sponsored workers’ compensation reinsurance organizations</td>
</tr>
<tr class="even">
<td>501(c)(28)</td>
<td>National railroad retirement investment trust</td>
</tr>
<tr class="odd">
<td>501(c)(29)</td>
<td>Qualified nonprofit health insurance issuers</td>
</tr>
</tbody>
</table>
</section>
<section id="frcd---filing-requirement-code" class="level2">
<h2 class="anchored" data-anchor-id="frcd---filing-requirement-code">FRCD - filing requirement code</h2>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 82%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Value</th>
<th>Description</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>000</td>
<td>990 - Not required to file (all other)</td>
<td></td>
</tr>
<tr class="even">
<td>001</td>
<td>990PF Required - 990 not required to file (all other)</td>
<td></td>
</tr>
<tr class="odd">
<td>010</td>
<td>990 (all other) or 990EZ return</td>
<td></td>
</tr>
<tr class="even">
<td>011</td>
<td>990PF Required (all other)</td>
<td></td>
</tr>
<tr class="odd">
<td>020</td>
<td>990 - Required to file Form 990-N (Income less than $25,000 per year)</td>
<td></td>
</tr>
<tr class="even">
<td>021</td>
<td>990PF Required - 990 Required to file Form 990-N (Income less than $25,000 per year)</td>
<td></td>
</tr>
<tr class="odd">
<td>030</td>
<td>990 - Group return</td>
<td></td>
</tr>
<tr class="even">
<td>031</td>
<td>990PF Required - Group return</td>
<td></td>
</tr>
<tr class="odd">
<td>040</td>
<td>990 - Required to file Form 990-BL, Black Lung Trusts</td>
<td></td>
</tr>
<tr class="even">
<td>041</td>
<td>990PF Required - 990 Required to file Form 990-BL, Black Lung Trusts</td>
<td></td>
</tr>
<tr class="odd">
<td>060</td>
<td>990 - Not required to file (church)</td>
<td></td>
</tr>
<tr class="even">
<td>061</td>
<td>990PF Required - Not required to file (church)</td>
<td></td>
</tr>
<tr class="odd">
<td>070</td>
<td>990 - Government 501(c)(1)</td>
<td></td>
</tr>
<tr class="even">
<td>071</td>
<td>990PF Required - Government 501(c)(1)</td>
<td></td>
</tr>
<tr class="odd">
<td>130</td>
<td>990 - Not required to file (religious organization)</td>
<td></td>
</tr>
<tr class="even">
<td>131</td>
<td>990PF Required - Not required to file (religious organization)</td>
<td></td>
</tr>
<tr class="odd">
<td>140</td>
<td>990 - Not required to file (instrumentalities of states or political subdivisions)</td>
<td></td>
</tr>
<tr class="even">
<td>141</td>
<td>990PF Required - Not required to file (instrumentalities of states or political subdivisions)</td>
<td></td>
</tr>
</tbody>
</table>

</section>
</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-irs-who-must-file" class="csl-entry" role="listitem">
<span>“Annual Exempt Organization Return: Who Must File.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/annual-exempt-organization-return-who-must-file">https://www.irs.gov/charities-non-profits/annual-exempt-organization-return-who-must-file</a>.
</div>
<div id="ref-irs-charitable-trusts" class="csl-entry" role="listitem">
<span>“Charitable Trusts.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/private-foundations/charitable-trusts">https://www.irs.gov/charities-non-profits/private-foundations/charitable-trusts</a>.
</div>
<div id="ref-irs-def-of-exempt-op" class="csl-entry" role="listitem">
<span>“Definition of Exempt Operating Foundation.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/private-foundations/definition-of-exempt-operating-foundation">https://www.irs.gov/charities-non-profits/private-foundations/definition-of-exempt-operating-foundation</a>.
</div>
<div id="ref-irs-disqualified" class="csl-entry" role="listitem">
<span>“’Disqualified Individual’ – Exempt Operating Foundation.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/private-foundations/disqualified-individual-exempt-operating-foundation">https://www.irs.gov/charities-non-profits/private-foundations/disqualified-individual-exempt-operating-foundation</a>.
</div>
<div id="ref-irs-exempt-op" class="csl-entry" role="listitem">
<span>“Exempt Operating Foundations.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/private-foundations/exempt-operating-foundations">https://www.irs.gov/charities-non-profits/private-foundations/exempt-operating-foundations</a>.
</div>
<div id="ref-irs-exempt-purposes" class="csl-entry" role="listitem">
<span>“Exempt Purposes – Internal Revenue Code Section 501(c)(3).”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/charitable-organizations/exempt-purposes-internal-revenue-code-section-501c3">https://www.irs.gov/charities-non-profits/charitable-organizations/exempt-purposes-internal-revenue-code-section-501c3</a>.
</div>
<div id="ref-irs-grantmaking" class="csl-entry" role="listitem">
<span>“Grant-Making Foundations.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/private-foundations/grant-making-foundations">https://www.irs.gov/charities-non-profits/private-foundations/grant-making-foundations</a>.
</div>
<div id="ref-irs-form-5227" class="csl-entry" role="listitem">
<span>“Instructions for Form 5227 (2022).”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/instructions/i5227">https://www.irs.gov/instructions/i5227</a>.
</div>
<div id="ref-irs-instructions-8940" class="csl-entry" role="listitem">
<span>“Instructions for Form 8940 (04/2023).”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/instructions/i8940">https://www.irs.gov/instructions/i8940</a>.
</div>
<div id="ref-irs-990-instructions" class="csl-entry" role="listitem">
<span>“Instructions for Form 990 Return of Organization Exempt from Income Tax (2022).”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/instructions/i990">https://www.irs.gov/instructions/i990</a>.
</div>
<div id="ref-irs-990ez-instructions" class="csl-entry" role="listitem">
<span>“Instructions for Form 990-EZ (2022).”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/instructions/i990ez">https://www.irs.gov/instructions/i990ez</a>.
</div>
<div id="ref-irs-990pf-instructions" class="csl-entry" role="listitem">
<span>“Instructions for Form 990-PF (2022).”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/instructions/i990pf">https://www.irs.gov/instructions/i990pf</a>.
</div>
<div id="ref-irs-private-foundations" class="csl-entry" role="listitem">
<span>“Private Foundations.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/charitable-organizations/private-foundations">https://www.irs.gov/charities-non-profits/charitable-organizations/private-foundations</a>.
</div>
<div id="ref-irs-private-op" class="csl-entry" role="listitem">
<span>“Private Operating Foundations.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/private-foundations/private-operating-foundations">https://www.irs.gov/charities-non-profits/private-foundations/private-operating-foundations</a>.
</div>
<div id="ref-irs-2014b" class="csl-entry" role="listitem">
Service, Internal Revenue. 2014. <span>“Form 1023-EZ: Streamlined Application for Recognition of Exemption Under Section 501(c)(3) of the Internal Revenue Code.”</span> Washington, DC. <a href="https://www.irs.gov/pub/irs-prior/f1023ez--2014.pdf">https://www.irs.gov/pub/irs-prior/f1023ez--2014.pdf</a>.
</div>
<div id="ref-irs-2020a" class="csl-entry" role="listitem">
———. 2020. <span>“Form 1023: Application for Recognition of Exemption Under Section 501(c)(3) of the Internal Revenue Code.”</span> Washington, DC. <a href="https://www.pay.gov/public/form/preview/pdf/104">https://www.pay.gov/public/form/preview/pdf/104</a>.
</div>
<div id="ref-irs-2022f" class="csl-entry" role="listitem">
———. 2022. <span>“Schedule a (Form 990): Public Charity Status and Public Support.”</span> Washington, DC. <a href="https://www.irs.gov/pub/irs-pdf/f990sa.pdf">https://www.irs.gov/pub/irs-pdf/f990sa.pdf</a>.
</div>
<div id="ref-irs-2023c" class="csl-entry" role="listitem">
———. 2023. <span>“Tax-Exempt Status for Your Organization.”</span> Washington, DC. <a href="https://www.irs.gov/pub/irs-pdf/p557.pdf">https://www.irs.gov/pub/irs-pdf/p557.pdf</a>.
</div>
<div id="ref-irs-split-interest-trust-stats" class="csl-entry" role="listitem">
<span>“SOI Tax Stats - Split-Interest Trust Statistics.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/statistics/soi-tax-stats-split-interest-trust-statistics">https://www.irs.gov/statistics/soi-tax-stats-split-interest-trust-statistics</a>.
</div>
<div id="ref-irs-501c17" class="csl-entry" role="listitem">
<span>“Supplemental Unemployment Benefits Trust - 501(c)(17).”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/other-non-profits/supplemental-unemployment-benefits-trust-501c17">https://www.irs.gov/charities-non-profits/other-non-profits/supplemental-unemployment-benefits-trust-501c17</a>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p><span class="citation" data-cites="irs-exempt-purposes">(<a href="#ref-irs-exempt-purposes" role="doc-biblioref"><span>“Exempt Purposes – Internal Revenue Code Section 501(c)(3),”</span> n.d.</a>)</span><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><span class="citation" data-cites="irs-instructions-8940">(<a href="#ref-irs-instructions-8940" role="doc-biblioref"><span>“Instructions for Form 8940 (04/2023),”</span> n.d.</a>)</span><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><span class="citation" data-cites="irs-who-must-file">(<a href="#ref-irs-who-must-file" role="doc-biblioref"><span>“Annual Exempt Organization Return: Who Must File,”</span> n.d.</a>)</span><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><span class="citation" data-cites="irs-private-op">(<a href="#ref-irs-private-op" role="doc-biblioref"><span>“Private Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><span class="citation" data-cites="irs-exempt-op">(<a href="#ref-irs-exempt-op" role="doc-biblioref"><span>“Exempt Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p><span class="citation" data-cites="irs-disqualified">(<a href="#ref-irs-disqualified" role="doc-biblioref"><span>“’Disqualified Individual’ – Exempt Operating Foundation,”</span> n.d.</a>)</span><a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p><span class="citation" data-cites="irs-grantmaking">(<a href="#ref-irs-grantmaking" role="doc-biblioref"><span>“Grant-Making Foundations,”</span> n.d.</a>)</span><a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p><span class="citation" data-cites="irs-def-of-exempt-op">(<a href="#ref-irs-def-of-exempt-op" role="doc-biblioref"><span>“Definition of Exempt Operating Foundation,”</span> n.d.</a>)</span><a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p><span class="citation" data-cites="irs-990pf-instructions">(<a href="#ref-irs-990pf-instructions" role="doc-biblioref"><span>“Instructions for Form 990-PF (2022),”</span> n.d.</a>)</span><a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p><span class="citation" data-cites="irs-private-op">(<a href="#ref-irs-private-op" role="doc-biblioref"><span>“Private Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p><span class="citation" data-cites="irs-exempt-op">(<a href="#ref-irs-exempt-op" role="doc-biblioref"><span>“Exempt Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p><span class="citation" data-cites="irs-private-foundations">(<a href="#ref-irs-private-foundations" role="doc-biblioref"><span>“Private Foundations,”</span> n.d.</a>)</span><a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p><span class="citation" data-cites="irs-501c17">(<a href="#ref-irs-501c17" role="doc-biblioref"><span>“Supplemental Unemployment Benefits Trust - 501(c)(17),”</span> n.d.</a>)</span><a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p><span class="citation" data-cites="irs-501c17">(<a href="#ref-irs-501c17" role="doc-biblioref"><span>“Supplemental Unemployment Benefits Trust - 501(c)(17),”</span> n.d.</a>)</span><a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p><span class="citation" data-cites="irs-501c17">(<a href="#ref-irs-501c17" role="doc-biblioref"><span>“Supplemental Unemployment Benefits Trust - 501(c)(17),”</span> n.d.</a>)</span><a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p><span class="citation" data-cites="irs-501c17">(<a href="#ref-irs-501c17" role="doc-biblioref"><span>“Supplemental Unemployment Benefits Trust - 501(c)(17),”</span> n.d.</a>)</span><a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p><span class="citation" data-cites="irs-charitable-trusts">(<a href="#ref-irs-charitable-trusts" role="doc-biblioref"><span>“Charitable Trusts,”</span> n.d.</a>)</span><a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p><span class="citation" data-cites="irs-charitable-trusts">(<a href="#ref-irs-charitable-trusts" role="doc-biblioref"><span>“Charitable Trusts,”</span> n.d.</a>)</span><a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p><span class="citation" data-cites="irs-990ez-instructions irs-990-instructions">(<a href="#ref-irs-990ez-instructions" role="doc-biblioref"><span>“Instructions for Form 990-EZ (2022),”</span> n.d.</a>; <a href="#ref-irs-990-instructions" role="doc-biblioref"><span>“Instructions for Form 990 Return of Organization Exempt from Income Tax (2022),”</span> n.d.</a>)</span><a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20"><p><span class="citation" data-cites="irs-990pf-instructions">(<a href="#ref-irs-990pf-instructions" role="doc-biblioref"><span>“Instructions for Form 990-PF (2022),”</span> n.d.</a>)</span><a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn21"><p><span class="citation" data-cites="irs-split-interest-trust-stats">(<a href="#ref-irs-split-interest-trust-stats" role="doc-biblioref"><span>“SOI Tax Stats - Split-Interest Trust Statistics,”</span> n.d.</a>)</span><a href="#fnref21" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn22"><p><span class="citation" data-cites="irs-form-5227">(<a href="#ref-irs-form-5227" role="doc-biblioref"><span>“Instructions for Form 5227 (2022),”</span> n.d.</a>)</span><a href="#fnref22" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn23"><p><span class="citation" data-cites="irs-form-5227">(<a href="#ref-irs-form-5227" role="doc-biblioref"><span>“Instructions for Form 5227 (2022),”</span> n.d.</a>)</span><a href="#fnref23" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn24"><p>I.R.C. § 120(e)<a href="#fnref24" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn25"><p>Omnibus Budget Reconciliation Act of 1987<a href="#fnref25" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>