<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>NCCS Research Guide - 7&nbsp; Foundations, Trusts, and Grant-Making Organizations</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./standard-04.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="style.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./standard-10.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Foundations, Trusts, and Grant-Making Organizations</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./img/logo-white.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">NCCS Research Guide</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sector-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./standard-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./standard-02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./standard-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./standard-04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./standard-10.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Foundations, Trusts, and Grant-Making Organizations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#c3-foundations-trusts-and-grant-making-organizations" id="toc-c3-foundations-trusts-and-grant-making-organizations" class="nav-link active" data-scroll-target="#c3-foundations-trusts-and-grant-making-organizations"><span class="header-section-number">7.1</span> 501(c)(3) foundations, trusts, and grant-making organizations</a>
  <ul class="collapse">
  <li><a href="#c3-private-foundations" id="toc-c3-private-foundations" class="nav-link" data-scroll-target="#c3-private-foundations"><span class="header-section-number">7.1.1</span> 501(c)(3) private foundations</a></li>
  <li><a href="#c3-public-foundations-trusts-and-grant-making-organizations" id="toc-c3-public-foundations-trusts-and-grant-making-organizations" class="nav-link" data-scroll-target="#c3-public-foundations-trusts-and-grant-making-organizations"><span class="header-section-number">7.1.2</span> 501(c)(3) public foundations, trusts, and grant-making organizations</a></li>
  <li><a href="#cothers-public-community-foundation" id="toc-cothers-public-community-foundation" class="nav-link" data-scroll-target="#cothers-public-community-foundation"><span class="header-section-number">7.1.3</span> 501(c)(others) public: community foundation</a></li>
  <li><a href="#cothers-public-supporting-organization---single-organization-support" id="toc-cothers-public-supporting-organization---single-organization-support" class="nav-link" data-scroll-target="#cothers-public-supporting-organization---single-organization-support"><span class="header-section-number">7.1.4</span> 501(c)(others) public: supporting organization - single organization support</a></li>
  <li><a href="#cothers-public-supporting-organization---multiple-organization-support" id="toc-cothers-public-supporting-organization---multiple-organization-support" class="nav-link" data-scroll-target="#cothers-public-supporting-organization---multiple-organization-support"><span class="header-section-number">7.1.5</span> 501(c)(others) public: supporting organization - multiple organization support</a></li>
  <li><a href="#cothers-public-other-public-foundation" id="toc-cothers-public-other-public-foundation" class="nav-link" data-scroll-target="#cothers-public-other-public-foundation"><span class="header-section-number">7.1.6</span> 501(c)(others) public: other public foundation</a></li>
  <li><a href="#a1-charitable-trust---treated-as-a-private-foundation" id="toc-a1-charitable-trust---treated-as-a-private-foundation" class="nav-link" data-scroll-target="#a1-charitable-trust---treated-as-a-private-foundation"><span class="header-section-number">7.1.7</span> 4947(a)(1) charitable trust - treated as a private foundation</a></li>
  <li><a href="#a1-charitable-trust---not-treated-as-a-private-foundation" id="toc-a1-charitable-trust---not-treated-as-a-private-foundation" class="nav-link" data-scroll-target="#a1-charitable-trust---not-treated-as-a-private-foundation"><span class="header-section-number">7.1.8</span> 4947(a)(1) charitable trust - not treated as a private foundation</a></li>
  <li><a href="#a2-split-interest-charitable-trust" id="toc-a2-split-interest-charitable-trust" class="nav-link" data-scroll-target="#a2-split-interest-charitable-trust"><span class="header-section-number">7.1.9</span> 4947(a)(2) split-interest charitable trust</a></li>
  <li><a href="#not-a-foundation-trust-or-grant-making-organization" id="toc-not-a-foundation-trust-or-grant-making-organization" class="nav-link" data-scroll-target="#not-a-foundation-trust-or-grant-making-organization"><span class="header-section-number">7.1.10</span> Not a foundation, trust, or grant-making organization</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Foundations, Trusts, and Grant-Making Organizations</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>This chapter explains NCCS’s taxonomy for foundations, trusts, and grant-making organizations:</p>
<table class="table">
<colgroup>
<col style="width: 0%">
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 1%">
<col style="width: 9%">
<col style="width: 82%">
</colgroup>
<thead>
<tr class="header">
<th>Value</th>
<th>Group</th>
<th>Subtype</th>
<th>501(c)(3) private foundation subtype</th>
<th>Subsection</th>
<th>Description</th>
<th>Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>not a foundation</td>
<td>NA</td>
<td>NA</td>
<td>NA</td>
<td>Not a foundation, trust, or grant-making organization</td>
<td>FNDNCD != 2 &amp; FNDNCD != 3 &amp; FNDNCD != 4 &amp; NTEECC != “T20” &amp; NTEECC != “T21” &amp; NTEECC != “T22” &amp; NTEECC != “T23” &amp; NTEECC != “T30” &amp; NTEECC != “T31” &amp; NTEECC != “A11” &amp; NTEECC != “B11” &amp; NTEECC != “C11” &amp; NTEECC != “D11” &amp; NTEECC != “E11” &amp; NTEECC != “F11” &amp; NTEECC != “G11” &amp; NTEECC != “H11” &amp; NTEECC != “I11” &amp; NTEECC != “J11” &amp; NTEECC != “K11” &amp; NTEECC != “L11” &amp; NTEECC != “M11” &amp; NTEECC != “N11” &amp; NTEECC != “O11” &amp; NTEECC != “P11” &amp; NTEECC != “Q11” &amp; NTEECC != “R11” &amp; NTEECC != “S11” &amp; NTEECC != “T11” &amp; NTEECC != “U11” &amp; NTEECC != “V11” &amp; NTEECC != “W11” &amp; NTEECC != “X11” &amp; NTEECC != “Y11” &amp; NTEECC != “A12” &amp; NTEECC != “B12” &amp; NTEECC != “C12” &amp; NTEECC != “D12” &amp; NTEECC != “E12” &amp; NTEECC != “F12” &amp; NTEECC != “G12” &amp; NTEECC != “H12” &amp; NTEECC != “I12” &amp; NTEECC != “J12” &amp; NTEECC != “K12” &amp; NTEECC != “L12” &amp; NTEECC != “M12” &amp; NTEECC != “N12” &amp; NTEECC != “O12” &amp; NTEECC != “P12” &amp; NTEECC != “Q12” &amp; NTEECC != “R12” &amp; NTEECC != “S12” &amp; NTEECC != “T12” &amp; NTEECC != “U12” &amp; NTEECC != “V12” &amp; NTEECC != “W12” &amp; NTEECC != “X12” &amp; NTEECC != “Y12” &amp; SUBSECCD != 90 &amp; SUBSECCD != 91 &amp; SUBSECCD != 92</td>
</tr>
<tr class="even">
<td>1</td>
<td>private</td>
<td>corporate</td>
<td>private operating</td>
<td>501(c)(3)</td>
<td>501(c)(3) private: private operating foundation (IRS status) &amp; corporate foundation (NTEE code)</td>
<td>SUBSECCD == 3 &amp; FNDNCD == 3 &amp; NTEECC == “T21”</td>
</tr>
<tr class="odd">
<td>2</td>
<td>private</td>
<td>corporate</td>
<td>exempt operating</td>
<td>501(c)(3)</td>
<td>501(c)(3) private: exempt operating foundation (IRS status) &amp; corporate foundation (NTEE code)</td>
<td>SUBSECCD == 3 &amp; FNDNCD == 2 &amp; NTEECC == “T21”</td>
</tr>
<tr class="even">
<td>3</td>
<td>private</td>
<td>corporate</td>
<td>grant-making (private nonoperating)</td>
<td>501(c)(3)</td>
<td>501(c)(3) private: grant-making (private nonoperating) foundation (IRS status) &amp; corporate foundation (NTEE code)</td>
<td>SUBSECCD == 3 &amp; FNDNCD == 4 &amp; NTEECC == “T21”</td>
</tr>
<tr class="odd">
<td>4</td>
<td>private</td>
<td>independent</td>
<td>private operating</td>
<td>501(c)(3)</td>
<td>501(c)(3) private: private operating foundation (IRS status) &amp; private independent foundation (NTEE code)</td>
<td>SUBSECCD == 3 &amp; FNDNCD == 3 &amp; NTEECC == “T22”</td>
</tr>
<tr class="even">
<td>5</td>
<td>private</td>
<td>independent</td>
<td>exempt operating</td>
<td>501(c)(3)</td>
<td>501(c)(3) private: exempt operating foundation (IRS status) &amp; private independent foundation (NTEE code)</td>
<td>SUBSECCD == 3 &amp; FNDNCD == 2 &amp; NTEECC == “T22”</td>
</tr>
<tr class="odd">
<td>6</td>
<td>private</td>
<td>independent</td>
<td>grant-making (private nonoperating)</td>
<td>501(c)(3)</td>
<td>501(c)(3) private: grant-making (private nonoperating) foundation (IRS status) &amp; private independent foundation (NTEE code)</td>
<td>SUBSECCD == 3 &amp; FNDNCD == 4 &amp; NTEECC == “T22”</td>
</tr>
<tr class="even">
<td>7</td>
<td>private</td>
<td>operating</td>
<td>private operating</td>
<td>501(c)(3)</td>
<td>501(c)(3) private: private operating foundation (IRS status) &amp; private operating foundation (NTEE code)</td>
<td>SUBSECCD == 3 &amp; FNDNCD == 3 &amp; NTEECC == “T23”</td>
</tr>
<tr class="odd">
<td>8</td>
<td>private</td>
<td>operating</td>
<td>exempt operating</td>
<td>501(c)(3)</td>
<td>501(c)(3) private: exempt operating foundation (IRS status) &amp; private operating foundation (NTEE code)</td>
<td>SUBSECCD == 3 &amp; FNDNCD == 2 &amp; NTEECC == “T23”</td>
</tr>
<tr class="even">
<td>9</td>
<td>private</td>
<td>operating</td>
<td>grant-making (private nonoperating)</td>
<td>501(c)(3)</td>
<td>501(c)(3) private: grant-making (private nonoperating) foundation (IRS status) &amp; private operating foundation (NTEE code)</td>
<td>SUBSECCD == 3 &amp; FNDNCD == 4 &amp; NTEECC == “T23”</td>
</tr>
<tr class="odd">
<td>10</td>
<td>private</td>
<td>other</td>
<td>private operating</td>
<td>501(c)(3)</td>
<td>501(c)(3) private: private operating foundation (IRS status), other (NTEE code)</td>
<td>SUBSECCD == 3 &amp; FNDNCD == 3 &amp; NTEECC != “T21” &amp; NTEECC != “T22” &amp; NTEECC != “T23”</td>
</tr>
<tr class="even">
<td>11</td>
<td>private</td>
<td>other</td>
<td>exempt operating</td>
<td>501(c)(3)</td>
<td>501(c)(3) private: exempt operating foundation (IRS status), other (NTEE code)</td>
<td>SUBSECCD == 3 &amp; FNDNCD == 2 &amp; NTEECC != “T21” &amp; NTEECC != “T22” &amp; NTEECC != “T23”</td>
</tr>
<tr class="odd">
<td>12</td>
<td>private</td>
<td>other</td>
<td>grant-making (private nonoperating)</td>
<td>501(c)(3)</td>
<td>501(c)(3) private: grant-making (private nonoperating) foundation (IRS status), other (NTEE code)</td>
<td>SUBSECCD == 3 &amp; FNDNCD == 4 &amp; NTEECC != “T21” &amp; NTEECC != “T22” &amp; NTEECC != “T23”</td>
</tr>
<tr class="even">
<td>13</td>
<td>public</td>
<td>community</td>
<td>NA</td>
<td>501(c)(3)</td>
<td>501(c)(3) public: community foundation</td>
<td>SUBSECCD == 3 &amp; FNDNCD != 2 &amp; FNDNCD != 3 &amp; FNDNCD != 4 &amp; NTEECC == “T31”</td>
</tr>
<tr class="odd">
<td>14</td>
<td>public</td>
<td>single organization support</td>
<td>NA</td>
<td>501(c)(3)</td>
<td>501(c)(3) public: supporting organization - single organization support</td>
<td>SUBSECCD == 3 &amp; FNDNCD != 2 &amp; FNDNCD != 3 &amp; FNDNCD != 4 &amp; ( NTEECC == “A11” | NTEECC == “B11” | NTEECC == “C11” | NTEECC == “D11” | NTEECC == “E11” | NTEECC == “F11” | NTEECC == “G11” | NTEECC == “H11” | NTEECC == “I11” | NTEECC == “J11” | NTEECC == “K11” | NTEECC == “L11” | NTEECC == “M11” | NTEECC == “N11” | NTEECC == “O11” | NTEECC == “P11” | NTEECC == “Q11” | NTEECC == “R11” | NTEECC == “S11” | NTEECC == “T11” | NTEECC == “U11” | NTEECC == “V11” | NTEECC == “W11” | NTEECC == “X11” | NTEECC == “Y11” )</td>
</tr>
<tr class="even">
<td>15</td>
<td>public</td>
<td>multiple organization support</td>
<td>NA</td>
<td>501(c)(3)</td>
<td>501(c)(3) public: supporting organization - multiple organization support</td>
<td>SUBSECCD == 3 &amp; FNDNCD != 2 &amp; FNDNCD != 3 &amp; FNDNCD != 4 &amp; ( NTEECC == “A12” | NTEECC == “B12” | NTEECC == “C12” | NTEECC == “D12” | NTEECC == “E12” | NTEECC == “F12” | NTEECC == “G12” | NTEECC == “H12” | NTEECC == “I12” | NTEECC == “J12” | NTEECC == “K12” | NTEECC == “L12” | NTEECC == “M12” | NTEECC == “N12” | NTEECC == “O12” | NTEECC == “P12” | NTEECC == “Q12” | NTEECC == “R12” | NTEECC == “S12” | NTEECC == “T12” | NTEECC == “U12” | NTEECC == “V12” | NTEECC == “W12” | NTEECC == “X12” | NTEECC == “Y12” )</td>
</tr>
<tr class="odd">
<td>16</td>
<td>public</td>
<td>other</td>
<td>NA</td>
<td>501(c)(3)</td>
<td>501(c)(3) public: other public foundation</td>
<td>SUBSECCD == 3 &amp; FNDNCD != 2 &amp; FNDNCD != 3 &amp; FNDNCD != 4 &amp; NTEECC == “T30”</td>
</tr>
<tr class="even">
<td>17</td>
<td>public</td>
<td>community</td>
<td>NA</td>
<td>501(c)(others)</td>
<td>501(c)(others) public: community foundation</td>
<td>SUBSECCD != 3 &amp; SUBSECCD != 90 &amp; SUBSECCD != 91 &amp; SUBSECCD != 92 &amp; FNDNCD != 2 &amp; FNDNCD != 3 &amp; FNDNCD != 4 &amp; NTEECC == “T31”</td>
</tr>
<tr class="odd">
<td>18</td>
<td>public</td>
<td>single organization support</td>
<td>NA</td>
<td>501(c)(others)</td>
<td>501(c)(others) public: supporting organization - single organization support</td>
<td>SUBSECCD != 3 &amp; SUBSECCD != 90 &amp; SUBSECCD != 91 &amp; SUBSECCD != 92 &amp; FNDNCD != 2 &amp; FNDNCD != 3 &amp; FNDNCD != 4 &amp; ( NTEECC == “A11” | NTEECC == “B11” | NTEECC == “C11” | NTEECC == “D11” | NTEECC == “E11” | NTEECC == “F11” | NTEECC == “G11” | NTEECC == “H11” | NTEECC == “I11” | NTEECC == “J11” | NTEECC == “K11” | NTEECC == “L11” | NTEECC == “M11” | NTEECC == “N11” | NTEECC == “O11” | NTEECC == “P11” | NTEECC == “Q11” | NTEECC == “R11” | NTEECC == “S11” | NTEECC == “T11” | NTEECC == “U11” | NTEECC == “V11” | NTEECC == “W11” | NTEECC == “X11” | NTEECC == “Y11” )</td>
</tr>
<tr class="even">
<td>19</td>
<td>public</td>
<td>multiple organization support</td>
<td>NA</td>
<td>501(c)(others)</td>
<td>501(c)(others) public: supporting organization - multiple organization support</td>
<td>SUBSECCD != 3 &amp; SUBSECCD != 90 &amp; SUBSECCD != 91 &amp; SUBSECCD != 92 &amp; FNDNCD != 2 &amp; FNDNCD != 3 &amp; FNDNCD != 4 &amp; ( NTEECC == “A12” | NTEECC == “B12” | NTEECC == “C12” | NTEECC == “D12” | NTEECC == “E12” | NTEECC == “F12” | NTEECC == “G12” | NTEECC == “H12” | NTEECC == “I12” | NTEECC == “J12” | NTEECC == “K12” | NTEECC == “L12” | NTEECC == “M12” | NTEECC == “N12” | NTEECC == “O12” | NTEECC == “P12” | NTEECC == “Q12” | NTEECC == “R12” | NTEECC == “S12” | NTEECC == “T12” | NTEECC == “U12” | NTEECC == “V12” | NTEECC == “W12” | NTEECC == “X12” | NTEECC == “Y12” )</td>
</tr>
<tr class="odd">
<td>20</td>
<td>public</td>
<td>other</td>
<td>NA</td>
<td>501(c)(others)</td>
<td>501(c)(others) public: other public foundation</td>
<td>SUBSECCD != 3 &amp; SUBSECCD != 90 &amp; SUBSECCD != 91 &amp; SUBSECCD != 92 &amp; FNDNCD != 2 &amp; FNDNCD != 3 &amp; FNDNCD != 4 &amp; NTEECC == “T30”</td>
</tr>
<tr class="even">
<td>21</td>
<td>private</td>
<td>NA</td>
<td>NA</td>
<td>4947(a)(1)</td>
<td>4947(a)(1) charitable trust - treated as a private foundation</td>
<td>SUBSECCD == 92</td>
</tr>
<tr class="odd">
<td>22</td>
<td>public</td>
<td>NA</td>
<td>NA</td>
<td>4947(a)(1)</td>
<td>4947(a)(1) charitable trust - not treated as a private foundation</td>
<td>SUBSECCD == 91</td>
</tr>
<tr class="even">
<td>23</td>
<td>private</td>
<td>NA</td>
<td>NA</td>
<td>4947(a)(2)</td>
<td>4947(a)(2) split-interest charitable trust</td>
<td>SUBSECCD == 90</td>
</tr>
</tbody>
</table>
<p>Each type of organization is described in detail below.</p>
<section id="c3-foundations-trusts-and-grant-making-organizations" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="c3-foundations-trusts-and-grant-making-organizations"><span class="header-section-number">7.1</span> 501(c)(3) foundations, trusts, and grant-making organizations</h2>
<p>To qualify as a 501(c)(3) organization, an organization must exist to advance one of the following exempt purposes:</p>
<ul>
<li><p>Charitable, which includes:</p>
<ul>
<li><p>“Relief of the poor, the distressed, or the underprivileged;</p></li>
<li><p>Advancement of religion;</p></li>
<li><p>Advancement of education or science;</p></li>
<li><p>Erection or maintenance of public buildings, monuments, or works;</p></li>
<li><p>Lessening the burdens of government;</p></li>
<li><p>Lessening neighborhood tensions;</p></li>
<li><p>Eliminating prejudice and discrimination;</p></li>
<li><p>Defending human and civil rights secured by law; and</p></li>
<li><p>Combating community deterioration and juvenile delinquency.”</p></li>
</ul></li>
<li><p>Religious</p></li>
<li><p>Educational</p></li>
<li><p>Scientific</p></li>
<li><p>Literary</p></li>
<li><p>Testing for public safety</p></li>
<li><p>Fostering national or international amateur sports competition</p></li>
<li><p>Prevention of cruelty to children or animals<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p></li>
</ul>
<p>501(c)(3) organizations indicate which exempt purpose(s) they advance when they file Form 1023 or 1023-EZ to apply for recognition of exemption from federal income tax (aka “tax-exempt status”) <span class="citation" data-cites="irs-2014b irs-2020a">(<a href="references.html#ref-irs-2014b" role="doc-biblioref">Service 2014</a>, <a href="references.html#ref-irs-2020a" role="doc-biblioref">2020</a>)</span>.</p>
<p>501(c)(3) organizations are either private foundations or public charities.</p>
<section id="c3-private-foundations" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="c3-private-foundations"><span class="header-section-number">7.1.1</span> 501(c)(3) private foundations</h3>
<p>The IRS distinguishes between three types of 501(c)(3) private foundations: private operating foundations, exempt operating foundations, and grant-making (private nonoperating) foundations.</p>
<p>501(c)(3) private foundations indicate whether they are a private operating foundation when they file Form 1023 <span class="citation" data-cites="irs-2020a">(<a href="references.html#ref-irs-2020a" role="doc-biblioref">Service 2020</a>)</span>. This option is not available to Form 1023-EZ filers <span class="citation" data-cites="irs-2014b">(<a href="references.html#ref-irs-2014b" role="doc-biblioref">Service 2014</a>)</span>. Later, private operating foundations that want recognition of exempt private operating foundation status must file Form 8940, Request for Miscellaneous Determination, to obtain a determination letter.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>501(c)(3) private foundations must file an annual Form 990-PF.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<section id="c3-private-private-operating-foundation-irs-status-corporate-foundation-ntee-code" class="level4" data-number="7.1.1.1">
<h4 data-number="7.1.1.1" class="anchored" data-anchor-id="c3-private-private-operating-foundation-irs-status-corporate-foundation-ntee-code"><span class="header-section-number">7.1.1.1</span> 501(c)(3) private: private operating foundation (IRS status) &amp; corporate foundation (NTEE code)</h4>
<p>Private operating foundations (IRS status) use most of their resources to actively conduct their exempt activities.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>Corporate foundations (NTEE code) are “private foundations whose grant funds are derived primarily from the contributions of a profit-making business organization.”<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>We can identify 501(c)(3) private operating foundations (IRS status) that are also corporate foundations (NTEE code) using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status) and NTEECC (NTEECC primary purpose). Values of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; values of 3 for FNDNCD indicate that an organization is a 501(c)(3) private operating foundation (IRS status), and values of T21 for NTEECC indicate that an organization is a corporate foundation (NTEE code).</p>
</section>
<section id="c3-private-exempt-operating-foundation-irs-status-corporate-foundation-ntee-code" class="level4" data-number="7.1.1.2">
<h4 data-number="7.1.1.2" class="anchored" data-anchor-id="c3-private-exempt-operating-foundation-irs-status-corporate-foundation-ntee-code"><span class="header-section-number">7.1.1.2</span> 501(c)(3) private: exempt operating foundation (IRS status) &amp; corporate foundation (NTEE code)</h4>
<p>Exempt operating foundations (IRS status) are private operating foundations that have been publicly supported for at least 10 years, have governing bodies with less than 25% disqualified individuals and that broadly represent the general public, and have no disqualified individuals as officers.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> “Disqualified individuals” in this case refers to substantial contributors to the foundation; owners of more than 20% of the total combined voting power of a corporation, the profits interest of a partnership, or the beneficial interest of a trust or unincorporated enterprise (if these entities are substantial contributors to the foundation); and family members of any individuals previously described.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<p>Corporate foundations (NTEE code) are “private foundations whose grant funds are derived primarily from the contributions of a profit-making business organization.”<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<p>We can identify 501(c)(3) exempt operating foundations (IRS status) that are also corporate foundations (NTEE code) using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status) and NTEECC (NTEECC primary purpose). Values of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; values of 2 for FNDNCD indicate that an organization is a 501(c)(3) exempt operating foundation (IRS status), and values of T21 for NTEECC indicate that an organization is a corporate foundation (NTEE code).</p>
</section>
<section id="c3-private-grant-making-private-nonoperating-foundation-irs-status-corporate-foundation-ntee-code" class="level4" data-number="7.1.1.3">
<h4 data-number="7.1.1.3" class="anchored" data-anchor-id="c3-private-grant-making-private-nonoperating-foundation-irs-status-corporate-foundation-ntee-code"><span class="header-section-number">7.1.1.3</span> 501(c)(3) private: grant-making (private nonoperating) foundation (IRS status) &amp; corporate foundation (NTEE code)</h4>
<p>Grant-making (private nonoperating) foundations (IRS status) are all other private foundations.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></p>
<p>Private operating foundations have the following advantages over grant-making (private nonoperating) foundations:</p>
<ul>
<li>They are exempt from the excise tax on failure to distribute income.</li>
<li>Donors can deduct contributions to these foundations to the extent of 50% of their adjusted gross income, instead of 30%.</li>
<li>Private foundations can make qualifying distributions to them, as long as they are not controlled by said private foundation.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></li>
</ul>
<p>In addition, <em>exempt</em> operating foundations have the following advantages over grant-making (private nonoperating) foundations:</p>
<ul>
<li>They are exempt from taxes on net investment income.</li>
<li>Private foundations can make grants to them without following expenditure responsibility requirements.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></li>
</ul>
<p>Corporate foundations (NTEE code) are “private foundations whose grant funds are derived primarily from the contributions of a profit-making business organization.”<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></p>
<p>We can identify 501(c)(3) grant-making (private nonoperating) foundations (IRS status) that are also corporate foundations (NTEE code) using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status) and NTEECC (NTEECC primary purpose). Values of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; values of 4 indicate that an organization is a 501(c)(3) grant-making (private nonoperating) foundation (IRS status), and values of T21 for NTEECC indicate that an organization is a corporate foundation (NTEE code).</p>
</section>
<section id="c3-private-private-operating-foundation-irs-status-private-independent-foundation-ntee-code" class="level4" data-number="7.1.1.4">
<h4 data-number="7.1.1.4" class="anchored" data-anchor-id="c3-private-private-operating-foundation-irs-status-private-independent-foundation-ntee-code"><span class="header-section-number">7.1.1.4</span> 501(c)(3) private: private operating foundation (IRS status) &amp; private independent foundation (NTEE code)</h4>
<p>Private operating foundations (IRS status) use most of their resources to actively conduct their exempt activities.<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a></p>
<p>Private independent foundations (NTEE code) are “private foundations that make grants based on charitable endowments. Because of their endowments, they are focused primarily on grantmaking and generally do not actively raise funds or seek public financial support. These are the most common type of private foundation They are generally endowed, usually from a single individual or family. Private foundations are considered family foundations if relatives or the original donor are still active on the board of trustees or in the operation of the foundation.”<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a></p>
<p>We can identify 501(c)(3) private operating foundations (IRS status) that are also private independent foundations (NTEE code) using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status) and NTEECC (NTEECC primary purpose). Values of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; values of 3 for FNDNCD indicate that an organization is a 501(c)(3) private operating foundation (IRS status), and values of T22 for NTEECC indicate that an organization is a private independent foundation (NTEE code).</p>
</section>
<section id="c3-private-exempt-operating-foundation-irs-status-private-independent-foundation-ntee-code-ntee-code" class="level4" data-number="7.1.1.5">
<h4 data-number="7.1.1.5" class="anchored" data-anchor-id="c3-private-exempt-operating-foundation-irs-status-private-independent-foundation-ntee-code-ntee-code"><span class="header-section-number">7.1.1.5</span> 501(c)(3) private: exempt operating foundation (IRS status) &amp; private independent foundation (NTEE code) (NTEE code)</h4>
<p>Exempt operating foundations (IRS status) are private operating foundations that have been publicly supported for at least 10 years, have governing bodies with less than 25% disqualified individuals and that broadly represent the general public, and have no disqualified individuals as officers.<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a> “Disqualified individuals” in this case refers to substantial contributors to the foundation; owners of more than 20% of the total combined voting power of a corporation, the profits interest of a partnership, or the beneficial interest of a trust or unincorporated enterprise (if these entities are substantial contributors to the foundation); and family members of any individuals previously described.<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a></p>
<p>Private independent foundations (NTEE code) are “private foundations that make grants based on charitable endowments. Because of their endowments, they are focused primarily on grantmaking and generally do not actively raise funds or seek public financial support. These are the most common type of private foundation They are generally endowed, usually from a single individual or family. Private foundations are considered family foundations if relatives or the original donor are still active on the board of trustees or in the operation of the foundation.”<a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a></p>
<p>We can identify 501(c)(3) exempt operating foundations (IRS status) that are also private independent foundations (NTEE code) using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status) and NTEECC (NTEECC primary purpose). Values of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; values of 2 for FNDNCD indicate that an organization is a 501(c)(3) exempt operating foundation (IRS status), and values of T22 for NTEECC indicate that an organization is a private independent foundation (NTEE code).</p>
</section>
<section id="c3-private-grant-making-private-nonoperating-foundation-irs-status-private-independent-foundation-ntee-code" class="level4" data-number="7.1.1.6">
<h4 data-number="7.1.1.6" class="anchored" data-anchor-id="c3-private-grant-making-private-nonoperating-foundation-irs-status-private-independent-foundation-ntee-code"><span class="header-section-number">7.1.1.6</span> 501(c)(3) private: grant-making (private nonoperating) foundation (IRS status) &amp; private independent foundation (NTEE code)</h4>
<p>Grant-making (private nonoperating) foundations (IRS status) are all other private foundations.<a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a></p>
<p>Private operating foundations have the following advantages over grant-making (private nonoperating) foundations:</p>
<ul>
<li>They are exempt from the excise tax on failure to distribute income.</li>
<li>Donors can deduct contributions to these foundations to the extent of 50% of their adjusted gross income, instead of 30%.</li>
<li>Private foundations can make qualifying distributions to them, as long as they are not controlled by said private foundation.<a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a></li>
</ul>
<p>In addition, <em>exempt</em> operating foundations have the following advantages over grant-making (private nonoperating) foundations:</p>
<ul>
<li>They are exempt from taxes on net investment income.</li>
<li>Private foundations can make grants to them without following expenditure responsibility requirements.<a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a></li>
</ul>
<p>Private independent foundations (NTEE code) are “private foundations that make grants based on charitable endowments. Because of their endowments, they are focused primarily on grantmaking and generally do not actively raise funds or seek public financial support. These are the most common type of private foundation They are generally endowed, usually from a single individual or family. Private foundations are considered family foundations if relatives or the original donor are still active on the board of trustees or in the operation of the foundation.”<a href="#fn21" class="footnote-ref" id="fnref21" role="doc-noteref"><sup>21</sup></a></p>
<p>We can identify 501(c)(3) grant-making (private nonoperating) foundations (IRS status) that are also private independent foundations (NTEE code) using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status) and NTEECC (NTEECC primary purpose). Values of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; valuesof 4 indicate that an organization is a 501(c)(3) grant-making (private nonoperating) foundation (IRS status), and values of T22 for NTEECC indicate that an organization is a private independent foundation (NTEE code).</p>
</section>
<section id="c3-private-private-operating-foundation-irs-status-private-operating-foundation-ntee-code" class="level4" data-number="7.1.1.7">
<h4 data-number="7.1.1.7" class="anchored" data-anchor-id="c3-private-private-operating-foundation-irs-status-private-operating-foundation-ntee-code"><span class="header-section-number">7.1.1.7</span> 501(c)(3) private: private operating foundation (IRS status) &amp; private operating foundation (NTEE code)</h4>
<p>Private operating foundations (IRS status) use most of their resources to actively conduct their exempt activities.<a href="#fn22" class="footnote-ref" id="fnref22" role="doc-noteref"><sup>22</sup></a></p>
<p>Private operating foundations (NTEE code) are “private foundations that use a bulk of their resources to provide charitable services or run charitable programs of their own. They make few, if any, grants to outside organizations and, like private independent foundations, they generally do not raise funds from the public.”<a href="#fn23" class="footnote-ref" id="fnref23" role="doc-noteref"><sup>23</sup></a></p>
<p>We can identify 501(c)(3) private operating foundations (IRS status) that are also private operating foundations (NTEE code) using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status) and NTEECC (NTEECC primary purpose). Values of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; values of 3 for FNDNCD indicate that an organization is a 501(c)(3) private operating foundation (IRS status), and values of T23 for NTEECC indicate that an organization is a private operating foundation (NTEE code).</p>
</section>
<section id="c3-private-exempt-operating-foundation-irs-status-private-operating-foundation-ntee-code" class="level4" data-number="7.1.1.8">
<h4 data-number="7.1.1.8" class="anchored" data-anchor-id="c3-private-exempt-operating-foundation-irs-status-private-operating-foundation-ntee-code"><span class="header-section-number">7.1.1.8</span> 501(c)(3) private: exempt operating foundation (IRS status) &amp; private operating foundation (NTEE code)</h4>
<p>Exempt operating foundations (IRS status) are private operating foundations that have been publicly supported for at least 10 years, have governing bodies with less than 25% disqualified individuals and that broadly represent the general public, and have no disqualified individuals as officers.<a href="#fn24" class="footnote-ref" id="fnref24" role="doc-noteref"><sup>24</sup></a> “Disqualified individuals” in this case refers to substantial contributors to the foundation; owners of more than 20% of the total combined voting power of a corporation, the profits interest of a partnership, or the beneficial interest of a trust or unincorporated enterprise (if these entities are substantial contributors to the foundation); and family members of any individuals previously described.<a href="#fn25" class="footnote-ref" id="fnref25" role="doc-noteref"><sup>25</sup></a></p>
<p>Private operating foundations (NTEE code) are “private foundations that use a bulk of their resources to provide charitable services or run charitable programs of their own. They make few, if any, grants to outside organizations and, like private independent foundations, they generally do not raise funds from the public.”<a href="#fn26" class="footnote-ref" id="fnref26" role="doc-noteref"><sup>26</sup></a></p>
<p>We can identify 501(c)(3) exempt operating foundations (IRS status) that are also private operating foundations (NTEE code) using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status) and NTEECC (NTEECC primary purpose). Values of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; values of 2 for FNDNCD indicate that an organization is a 501(c)(3) exempt operating foundation (IRS status), and values of T23 for NTEECC indicate that an organization is a private operating foundation (NTEE code).</p>
</section>
<section id="c3-private-grant-making-private-nonoperating-foundation-irs-status-private-operating-foundation-ntee-code" class="level4" data-number="7.1.1.9">
<h4 data-number="7.1.1.9" class="anchored" data-anchor-id="c3-private-grant-making-private-nonoperating-foundation-irs-status-private-operating-foundation-ntee-code"><span class="header-section-number">7.1.1.9</span> 501(c)(3) private: grant-making (private nonoperating) foundation (IRS status) &amp; private operating foundation (NTEE code)</h4>
<p>Grant-making (private nonoperating) foundations (IRS status) are all other private foundations.<a href="#fn27" class="footnote-ref" id="fnref27" role="doc-noteref"><sup>27</sup></a></p>
<p>Private operating foundations have the following advantages over grant-making (private nonoperating) foundations:</p>
<ul>
<li>They are exempt from the excise tax on failure to distribute income.</li>
<li>Donors can deduct contributions to these foundations to the extent of 50% of their adjusted gross income, instead of 30%.</li>
<li>Private foundations can make qualifying distributions to them, as long as they are not controlled by said private foundation.<a href="#fn28" class="footnote-ref" id="fnref28" role="doc-noteref"><sup>28</sup></a></li>
</ul>
<p>In addition, <em>exempt</em> operating foundations have the following advantages over grant-making (private nonoperating) foundations:</p>
<ul>
<li>They are exempt from taxes on net investment income.</li>
<li>Private foundations can make grants to them without following expenditure responsibility requirements.<a href="#fn29" class="footnote-ref" id="fnref29" role="doc-noteref"><sup>29</sup></a></li>
</ul>
<p>Private operating foundations (NTEE code) are “private foundations that use a bulk of their resources to provide charitable services or run charitable programs of their own. They make few, if any, grants to outside organizations and, like private independent foundations, they generally do not raise funds from the public.”<a href="#fn30" class="footnote-ref" id="fnref30" role="doc-noteref"><sup>30</sup></a></p>
<p>We can identify 501(c)(3) grant-making (private nonoperating) foundations (IRS status) that are also private operating foundations (NTEE code) using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status) and NTEECC (NTEECC primary purpose). Values of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; values of 4 indicate that an organization is a 501(c)(3) grant-making (private nonoperating) foundation (IRS status), and values of T23 for NTEECC indicate that an organization is a private operating foundation (NTEE code).</p>
</section>
<section id="c3-private-private-operating-foundation-irs-status-other-ntee-code" class="level4" data-number="7.1.1.10">
<h4 data-number="7.1.1.10" class="anchored" data-anchor-id="c3-private-private-operating-foundation-irs-status-other-ntee-code"><span class="header-section-number">7.1.1.10</span> 501(c)(3) private: private operating foundation (IRS status), other (NTEE code)</h4>
<p>Private operating foundations (IRS status) use most of their resources to actively conduct their exempt activities.<a href="#fn31" class="footnote-ref" id="fnref31" role="doc-noteref"><sup>31</sup></a></p>
<p>We can identify 501(c)(3) private operating foundations (IRS status) that are not corporate foundations, private independent foundations, or private operating foundations (NTEE codes) using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status) and NTEECC (NTEECC primary purpose). Values of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; values of 3 for FNDNCD indicate that an organization is a 501(c)(3) private operating foundation (IRS status), and values of anything other than T21, T22, and T23 for NTEECC indicate that an organization is not a corporate foundation, private independent foundation, or private operating foundation (NTEE codes).</p>
</section>
<section id="c3-private-exempt-operating-foundation-irs-status-other-ntee-code" class="level4" data-number="7.1.1.11">
<h4 data-number="7.1.1.11" class="anchored" data-anchor-id="c3-private-exempt-operating-foundation-irs-status-other-ntee-code"><span class="header-section-number">7.1.1.11</span> 501(c)(3) private: exempt operating foundation (IRS status), other (NTEE code)</h4>
<p>Exempt operating foundations (IRS status) are private operating foundations that have been publicly supported for at least 10 years, have governing bodies with less than 25% disqualified individuals and that broadly represent the general public, and have no disqualified individuals as officers.<a href="#fn32" class="footnote-ref" id="fnref32" role="doc-noteref"><sup>32</sup></a> “Disqualified individuals” in this case refers to substantial contributors to the foundation; owners of more than 20% of the total combined voting power of a corporation, the profits interest of a partnership, or the beneficial interest of a trust or unincorporated enterprise (if these entities are substantial contributors to the foundation); and family members of any individuals previously described.<a href="#fn33" class="footnote-ref" id="fnref33" role="doc-noteref"><sup>33</sup></a></p>
<p>We can identify 501(c)(3) exempt operating foundations (IRS status) that are not corporate foundations, private independent foundations, or private operating foundations (NTEE codes) using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status) and NTEECC (NTEECC primary purpose). Values of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; values of 2 for FNDNCD indicate that an organization is a 501(c)(3) exempt operating foundation (IRS status), and values of anything other than T21, T22, and T23 for NTEECC indicate that an organization is not a corporate foundation, private independent foundation, or private operating foundation (NTEE codes).</p>
</section>
<section id="c3-private-grant-making-private-nonoperating-foundation-irs-status-other-ntee-code" class="level4" data-number="7.1.1.12">
<h4 data-number="7.1.1.12" class="anchored" data-anchor-id="c3-private-grant-making-private-nonoperating-foundation-irs-status-other-ntee-code"><span class="header-section-number">7.1.1.12</span> 501(c)(3) private: grant-making (private nonoperating) foundation (IRS status), other (NTEE code)</h4>
<p>Grant-making (private nonoperating) foundations (IRS status) are all other private foundations.<a href="#fn34" class="footnote-ref" id="fnref34" role="doc-noteref"><sup>34</sup></a></p>
<p>Private operating foundations have the following advantages over grant-making (private nonoperating) foundations:</p>
<ul>
<li>They are exempt from the excise tax on failure to distribute income.</li>
<li>Donors can deduct contributions to these foundations to the extent of 50% of their adjusted gross income, instead of 30%.</li>
<li>Private foundations can make qualifying distributions to them, as long as they are not controlled by said private foundation.<a href="#fn35" class="footnote-ref" id="fnref35" role="doc-noteref"><sup>35</sup></a></li>
</ul>
<p>In addition, <em>exempt</em> operating foundations have the following advantages over grant-making (private nonoperating) foundations:</p>
<ul>
<li>They are exempt from taxes on net investment income.</li>
<li>Private foundations can make grants to them without following expenditure responsibility requirements.<a href="#fn36" class="footnote-ref" id="fnref36" role="doc-noteref"><sup>36</sup></a></li>
</ul>
<p>We can identify 501(c)(3) grant-making (private nonoperating) foundations (IRS status) that are not corporate foundations, private independent foundations, or private operating foundations (NTEE codes) using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status) and NTEECC (NTEECC primary purpose). alues of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; values of 4 for FNDNCD indicate that an organization is a 501(c)(3) grant-making (private nonoperating) foundation (IRS status), and values of anything other than T21, T22, and T23 for NTEECC indicate that an organization is not a corporate foundation, private independent foundation, or private operating foundation (NTEE codes).</p>
</section>
</section>
<section id="c3-public-foundations-trusts-and-grant-making-organizations" class="level3" data-number="7.1.2">
<h3 data-number="7.1.2" class="anchored" data-anchor-id="c3-public-foundations-trusts-and-grant-making-organizations"><span class="header-section-number">7.1.2</span> 501(c)(3) public foundations, trusts, and grant-making organizations</h3>
<p>To qualify as a 501(c)(3) public charity, rather than a 501(c)(3) private foundation, an organization must be one of the following:</p>
<ul>
<li><p>A church, convention of churches, or association of churches</p></li>
<li><p>A school</p></li>
<li><p>A hospital or cooperative hospital service organization</p></li>
<li><p>A medical research organization operated in conjunction with a hospital</p></li>
<li><p>An organization operated for the benefit of a college or university that is owned or operated by a governmental unit</p></li>
<li><p>A federal, state, or local government or governmental unit</p></li>
<li><p>An organization that normally receives a substantial part of its support from a governmental unit or from the general public</p></li>
<li><p>A community trust</p></li>
<li><p>An agricultural research organization operated in conjunction with a land-grant college or university or a non-land-grant college of agriculture</p></li>
<li><p>An organization that normally receives more than 33 and 1/3% of its support from contributions, membership fees, and gross receipts from activities related to its exempt functions and receives no more than 33 and 1/3 percent of its support from gross investment income and unrelated business taxable income from businesses acquired by the organization after June 30, 1975</p></li>
<li><p>An organization organized and operated exclusively for testing for public safety</p></li>
<li><p>A 509(a)(3) supporting organization, including the following types:</p>
<ul>
<li><p>Type I – those operated, supervised, or controlled by the supported organization(s) by giving the supported organization(s) the power to regularly appoint or elect a majority of the directors or trustees of the supporting organization</p></li>
<li><p>Type II – those supervised or controlled in connection with the supported organization(s) by having control or management of the supporting organization vested in the same persons that control or manage the supported organization(s)</p></li>
<li><p>Type III functionally integrated – those operated in connection with, and functionally integrated with, the supported organization(s)</p></li>
<li><p>Type III non-functionally integrated – those operated in connection with the supported organization(s) that are not functionally integrated <span class="citation" data-cites="irs-2022f">(<a href="references.html#ref-irs-2022f" role="doc-biblioref">Service 2022</a>)</span></p></li>
</ul></li>
</ul>
<p>501(c)(3) organizations indicate whether they are a public charity or a private foundation when they file Form 1023 or 1023-EZ, and if they are a public charity, they must select the reason they are not a private foundation <span class="citation" data-cites="irs-2014b irs-2020a">(<a href="references.html#ref-irs-2014b" role="doc-biblioref">Service 2014</a>, <a href="references.html#ref-irs-2020a" role="doc-biblioref">2020</a>)</span>. 501(c)(3) public charities also select the reason they are not a private foundation when they file Schedule A (Form 990) every year <span class="citation" data-cites="irs-2022f">(<a href="references.html#ref-irs-2022f" role="doc-biblioref">Service 2022</a>)</span>. Private foundations that later want to be reclassified as public charities must terminate their private foundation status and apply for public charity status.<a href="#fn37" class="footnote-ref" id="fnref37" role="doc-noteref"><sup>37</sup></a></p>
<p>The IRS imposes several taxes, restrictions, and requirements on private foundations that it does not place on public charities:</p>
<ul>
<li><p>Private foundations must pay excise taxes on their net investment income.</p></li>
<li><p>Private foundations must pay excise taxes on acts of self-dealing with disqualified individuals.</p></li>
<li><p>Private foundations must distribute a portion of their income annually for charitable purposes.</p></li>
<li><p>Private foundations must pay excise taxes on any excess holdings above 20% that it and all of its disqualified individuals have in the voting stock of a business enterprise.</p></li>
<li><p>Private foundations must pay excise taxes on jeopardizing investments (i.e., those that jeopardize the carrying out of exempt purposes).</p></li>
<li><p>Private foundations must pay excise taxes on expenditures that do not further exempt purposes, such as lobbying.<a href="#fn38" class="footnote-ref" id="fnref38" role="doc-noteref"><sup>38</sup></a></p></li>
</ul>
<p>Most 501(c)(3) public charities must file an annual Form 990-N, 990-EZ, or 990.<a href="#fn39" class="footnote-ref" id="fnref39" role="doc-noteref"><sup>39</sup></a></p>
<section id="c3-public-community-foundation" class="level4" data-number="7.1.2.1">
<h4 data-number="7.1.2.1" class="anchored" data-anchor-id="c3-public-community-foundation"><span class="header-section-number">7.1.2.1</span> 501(c)(3) public: community foundation</h4>
<p>Community foundations are “organizations that make grants for charitable purposes in a specific community or region. The funds available to a community foundation are usually derived from many donors and held in an endowment that is independently administered; income earned by the endowment is then used to make grants.”<a href="#fn40" class="footnote-ref" id="fnref40" role="doc-noteref"><sup>40</sup></a></p>
<p>We can identify 501(c)(3) community foundations using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status), and NTEECC (NTEECC primary purpose). Values of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; values of anything other than 2, 3, or 4 for FNDNCD indicate that an organization is not a private foundation; and values of T31 for NTEECC indicate that an organization is a community foundation.</p>
</section>
<section id="c3-public-supporting-organization---single-organization-support" class="level4" data-number="7.1.2.2">
<h4 data-number="7.1.2.2" class="anchored" data-anchor-id="c3-public-supporting-organization---single-organization-support"><span class="header-section-number">7.1.2.2</span> 501(c)(3) public: supporting organization - single organization support</h4>
<p>Supporting organizations that provide support to a single organization are “organizations existing as a support and fund-raising entity for a single institution.”<a href="#fn41" class="footnote-ref" id="fnref41" role="doc-noteref"><sup>41</sup></a></p>
<p>We can identify 501(c)(3) supporting organizations that provide support to a single organization using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status), and NTEECC (NTEECC primary purpose). Values of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; values of anything other than 2, 3, or 4 for FNDNCD indicate that an organization is not a private foundation; and values of A11, B11, C11, D11, E11, F11, G11, H11, I11, J11, K11, L11, M11, N11, O11, P11, Q11, R11, S11, T11, U11, V11, W11, X11, and Y11 for NTEECC indicate that an organization is a supporting organization that provides support to a single organization.</p>
</section>
<section id="c3-public-supporting-organization---multiple-organization-support" class="level4" data-number="7.1.2.3">
<h4 data-number="7.1.2.3" class="anchored" data-anchor-id="c3-public-supporting-organization---multiple-organization-support"><span class="header-section-number">7.1.2.3</span> 501(c)(3) public: supporting organization - multiple organization support</h4>
<p>Supporting organizations that provide support to multiple organizations are “organizations that raise and distribute funds for multiple organizations.”<a href="#fn42" class="footnote-ref" id="fnref42" role="doc-noteref"><sup>42</sup></a></p>
<p>We can identify 501(c)(3) supporting organizations that provide support to multiple organizations using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status), and NTEECC (NTEECC primary purpose). Values of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; values of anything other than 2, 3, or 4 for FNDNCD indicate that an organization is not a private foundation; and values of A12, B12, C12, D12, E12, F12, G12, H12, I12, J12, K12, L12, M12, N12, O12, P12, Q12, R12, S12, T12, U12, V12, W12, X12, and Y12 for NTEECC indicate that an organization is a supporting organization that provides support to multiple organizations.</p>
</section>
<section id="c3-public-other-public-foundation" class="level4" data-number="7.1.2.4">
<h4 data-number="7.1.2.4" class="anchored" data-anchor-id="c3-public-other-public-foundation"><span class="header-section-number">7.1.2.4</span> 501(c)(3) public: other public foundation</h4>
<p>Public foundations are “organizations that derive their funding or support primarily from the general public in carrying our their social, educational, religious or other charitable activities serving the common welfare. Although public foundations may provide direct charitable services to the public as other nonprofits do, their primary focus is on grantmaking.”<a href="#fn43" class="footnote-ref" id="fnref43" role="doc-noteref"><sup>43</sup></a></p>
<p>We can identify other 501(c)(3) public foundations using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status), and NTEECC (NTEECC primary purpose). Values of 3 for SUBSECCD indicate that an organization is a 501(c)(3) organization; values of anything other than 2, 3, or 4 for FNDNCD indicate that an organization is not a private foundation; and values of T30 for NTEECC indicate that an organization is a public foundation.</p>
</section>
</section>
<section id="cothers-public-community-foundation" class="level3" data-number="7.1.3">
<h3 data-number="7.1.3" class="anchored" data-anchor-id="cothers-public-community-foundation"><span class="header-section-number">7.1.3</span> 501(c)(others) public: community foundation</h3>
<p>Community foundations are “organizations that make grants for charitable purposes in a specific community or region. The funds available to a community foundation are usually derived from many donors and held in an endowment that is independently administered; income earned by the endowment is then used to make grants.”<a href="#fn44" class="footnote-ref" id="fnref44" role="doc-noteref"><sup>44</sup></a></p>
<p>We can identify non-501(c)(3) community foundations using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status), and NTEECC (NTEECC primary purpose). Values of anything other than 3, 90, 91, or 92 for SUBSECCD indicate that an organization is a non-501(c)(3), non-4941(a)(1) charitable trust, non-4947(a)(2) split-interest charitable trust organization; values of anything other than 2, 3, or 4 for FNDNCD indicate that an organization is not a private foundation; and values of T31 for NTEECC indicate that an organization is a community foundation.</p>
</section>
<section id="cothers-public-supporting-organization---single-organization-support" class="level3" data-number="7.1.4">
<h3 data-number="7.1.4" class="anchored" data-anchor-id="cothers-public-supporting-organization---single-organization-support"><span class="header-section-number">7.1.4</span> 501(c)(others) public: supporting organization - single organization support</h3>
<p>Supporting organizations that provide support to a single organization are “organizations existing as a support and fund-raising entity for a single institution.”<a href="#fn45" class="footnote-ref" id="fnref45" role="doc-noteref"><sup>45</sup></a></p>
<p>We can identify non-501(c)(3) supporting organizations that provide support to a single organization using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status), and NTEECC (NTEECC primary purpose). Values of anything other than 3 for SUBSECCD indicate that an organization is a non-501(c)(3), non-4941(a)(1) charitable trust, non-4947(a)(2) split-interest charitable trust organization; values of anything other than 2, 3, or 4 for FNDNCD indicate that an organization is not a private foundation; and values of A11, B11, C11, D11, E11, F11, G11, H11, I11, J11, K11, L11, M11, N11, O11, P11, Q11, R11, S11, T11, U11, V11, W11, X11, and Y11 for NTEECC indicate that an organization is a supporting organization that provides support to a single organization.</p>
</section>
<section id="cothers-public-supporting-organization---multiple-organization-support" class="level3" data-number="7.1.5">
<h3 data-number="7.1.5" class="anchored" data-anchor-id="cothers-public-supporting-organization---multiple-organization-support"><span class="header-section-number">7.1.5</span> 501(c)(others) public: supporting organization - multiple organization support</h3>
<p>Supporting organizations that provide support to multiple organizations are “organizations that raise and distribute funds for multiple organizations.”<a href="#fn46" class="footnote-ref" id="fnref46" role="doc-noteref"><sup>46</sup></a></p>
<p>We can identify non-501(c)(3) supporting organizations that provide support to multiple organizations using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status), and NTEECC (NTEECC primary purpose). Values of anything other than 3 for SUBSECCD indicate that an organization is a non-501(c)(3), non-4941(a)(1) charitable trust, non-4947(a)(2) split-interest charitable trust organization; values of anything other than 2, 3, or 4 for FNDNCD indicate that an organization is not a private foundation; and values of A12, B12, C12, D12, E12, F12, G12, H12, I12, J12, K12, L12, M12, N12, O12, P12, Q12, R12, S12, T12, U12, V12, W12, X12, and Y12 for NTEECC indicate that an organization is a supporting organization that provides support to multiple organizations.</p>
</section>
<section id="cothers-public-other-public-foundation" class="level3" data-number="7.1.6">
<h3 data-number="7.1.6" class="anchored" data-anchor-id="cothers-public-other-public-foundation"><span class="header-section-number">7.1.6</span> 501(c)(others) public: other public foundation</h3>
<p>Public foundations are “organizations that derive their funding or support primarily from the general public in carrying our their social, educational, religious or other charitable activities serving the common welfare. Although public foundations may provide direct charitable services to the public as other nonprofits do, their primary focus is on grantmaking.”<a href="#fn47" class="footnote-ref" id="fnref47" role="doc-noteref"><sup>47</sup></a></p>
<p>We can identify other non-501(c)(3) public foundations using SUBSECCD (subsection code), FNDNCD (reason for 501(c)(3) status), and NTEECC (NTEECC primary purpose). Values of anything other than 3 for SUBSECCD indicate that an organization is a non-501(c)(3), non-4941(a)(1) charitable trust, non-4947(a)(2) split-interest charitable trust organization; values of anything other than 2, 3, or 4 for FNDNCD indicate that an organization is not a private foundation; and values of T30 for NTEECC indicate that an organization is a public foundation.</p>
</section>
<section id="a1-charitable-trust---treated-as-a-private-foundation" class="level3" data-number="7.1.7">
<h3 data-number="7.1.7" class="anchored" data-anchor-id="a1-charitable-trust---treated-as-a-private-foundation"><span class="header-section-number">7.1.7</span> 4947(a)(1) charitable trust - treated as a private foundation</h3>
<p>A 4947(a)(1) charitable trusts is “a trust that is not tax exempt, all of the unexpired interests of which are devoted to one or more charitable purposes, and for which a charitable contribution deduction was allowed under a specific section of the Internal Revenue Code.”<a href="#fn48" class="footnote-ref" id="fnref48" role="doc-noteref"><sup>48</sup></a></p>
<p>The IRS treats them as private foundations unless they meet one of the requirements for being a 501(c)(3) public charity. This means the IRS subjects them to the same taxes, restrictions, and requirements of private foundations, which are more stringent than those it places on public charities.<a href="#fn49" class="footnote-ref" id="fnref49" role="doc-noteref"><sup>49</sup></a></p>
<p>4947(a)(1) charitable trusts treated as private foundations must file an annual Form 990-PF.<a href="#fn50" class="footnote-ref" id="fnref50" role="doc-noteref"><sup>50</sup></a></p>
<p>We can identify 4947(a)(1) charitable trusts that are treated as private foundations using SUBSECCD (subsection code). Values of 92 indicate that an organization is a 4947(a)(1) charitable trust treated as a private foundation.</p>
</section>
<section id="a1-charitable-trust---not-treated-as-a-private-foundation" class="level3" data-number="7.1.8">
<h3 data-number="7.1.8" class="anchored" data-anchor-id="a1-charitable-trust---not-treated-as-a-private-foundation"><span class="header-section-number">7.1.8</span> 4947(a)(1) charitable trust - not treated as a private foundation</h3>
<p>A 4947(a)(1) charitable trusts is “a trust that is not tax exempt, all of the unexpired interests of which are devoted to one or more charitable purposes, and for which a charitable contribution deduction was allowed under a specific section of the Internal Revenue Code.”<a href="#fn51" class="footnote-ref" id="fnref51" role="doc-noteref"><sup>51</sup></a></p>
<p>The IRS treats them as private foundations unless they meet one of the requirements for being a 501(c)(3) public charity. This means that 4941(a)(1) charitable trusts that are not treated as private foundations are not subjected to the same taxes, restrictions, and requirements of private foundations, which are more stringent than those the IRS places on public charities.<a href="#fn52" class="footnote-ref" id="fnref52" role="doc-noteref"><sup>52</sup></a></p>
<p>4947(a)(1) charitable trusts not treated as private foundations must file an annual Form 990-EZ or 990.<a href="#fn53" class="footnote-ref" id="fnref53" role="doc-noteref"><sup>53</sup></a></p>
<p>We can identify 4947(a)(1) charitable trusts that are not treated as private foundations using SUBSECCD (subsection code). Values of 91 indicate that an organization is a 4947(a)(1) charitable trust not treated as a private foundation.</p>
</section>
<section id="a2-split-interest-charitable-trust" class="level3" data-number="7.1.9">
<h3 data-number="7.1.9" class="anchored" data-anchor-id="a2-split-interest-charitable-trust"><span class="header-section-number">7.1.9</span> 4947(a)(2) split-interest charitable trust</h3>
<p>4947(a)(2) split-interest charitable trusts “make distributions to both charitable and noncharitable beneficiaries, while providing tax benefits to their donor.”<a href="#fn54" class="footnote-ref" id="fnref54" role="doc-noteref"><sup>54</sup></a> They are not exempt from federal income tax.<a href="#fn55" class="footnote-ref" id="fnref55" role="doc-noteref"><sup>55</sup></a></p>
<p>The IRS treats them as private foundations.<a href="#fn56" class="footnote-ref" id="fnref56" role="doc-noteref"><sup>56</sup></a></p>
<p>4947(a)(2) split-interest charitable trusts must file an annual Form 5227: Split-Interest Trust Information Return.<a href="#fn57" class="footnote-ref" id="fnref57" role="doc-noteref"><sup>57</sup></a></p>
<p>We can identify 4947(a)(2) split-interest charitable trusts using SUBSECCD (subsection code). Values of 90 indicate that an organization is a 4947(a)(2) split-interest charitable trust.</p>
</section>
<section id="not-a-foundation-trust-or-grant-making-organization" class="level3" data-number="7.1.10">
<h3 data-number="7.1.10" class="anchored" data-anchor-id="not-a-foundation-trust-or-grant-making-organization"><span class="header-section-number">7.1.10</span> Not a foundation, trust, or grant-making organization</h3>
<p>Organizations not described above are coded as “not a foundation, trust, or grant-making organization.”</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-irs-who-must-file" class="csl-entry" role="listitem">
<span>“Annual Exempt Organization Return: Who Must File.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/annual-exempt-organization-return-who-must-file">https://www.irs.gov/charities-non-profits/annual-exempt-organization-return-who-must-file</a>.
</div>
<div id="ref-irs-charitable-trusts" class="csl-entry" role="listitem">
<span>“Charitable Trusts.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/private-foundations/charitable-trusts">https://www.irs.gov/charities-non-profits/private-foundations/charitable-trusts</a>.
</div>
<div id="ref-irs-def-of-exempt-op" class="csl-entry" role="listitem">
<span>“Definition of Exempt Operating Foundation.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/private-foundations/definition-of-exempt-operating-foundation">https://www.irs.gov/charities-non-profits/private-foundations/definition-of-exempt-operating-foundation</a>.
</div>
<div id="ref-irs-disqualified" class="csl-entry" role="listitem">
<span>“’Disqualified Individual’ – Exempt Operating Foundation.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/private-foundations/disqualified-individual-exempt-operating-foundation">https://www.irs.gov/charities-non-profits/private-foundations/disqualified-individual-exempt-operating-foundation</a>.
</div>
<div id="ref-irs-exempt-op" class="csl-entry" role="listitem">
<span>“Exempt Operating Foundations.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/private-foundations/exempt-operating-foundations">https://www.irs.gov/charities-non-profits/private-foundations/exempt-operating-foundations</a>.
</div>
<div id="ref-irs-exempt-purposes" class="csl-entry" role="listitem">
<span>“Exempt Purposes – Internal Revenue Code Section 501(c)(3).”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/charitable-organizations/exempt-purposes-internal-revenue-code-section-501c3">https://www.irs.gov/charities-non-profits/charitable-organizations/exempt-purposes-internal-revenue-code-section-501c3</a>.
</div>
<div id="ref-irs-grantmaking" class="csl-entry" role="listitem">
<span>“Grant-Making Foundations.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/private-foundations/grant-making-foundations">https://www.irs.gov/charities-non-profits/private-foundations/grant-making-foundations</a>.
</div>
<div id="ref-irs-form-5227" class="csl-entry" role="listitem">
<span>“Instructions for Form 5227 (2022).”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/instructions/i5227">https://www.irs.gov/instructions/i5227</a>.
</div>
<div id="ref-irs-instructions-8940" class="csl-entry" role="listitem">
<span>“Instructions for Form 8940 (04/2023).”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/instructions/i8940">https://www.irs.gov/instructions/i8940</a>.
</div>
<div id="ref-irs-990-instructions" class="csl-entry" role="listitem">
<span>“Instructions for Form 990 Return of Organization Exempt from Income Tax (2022).”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/instructions/i990">https://www.irs.gov/instructions/i990</a>.
</div>
<div id="ref-irs-990ez-instructions" class="csl-entry" role="listitem">
<span>“Instructions for Form 990-EZ (2022).”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/instructions/i990ez">https://www.irs.gov/instructions/i990ez</a>.
</div>
<div id="ref-irs-990pf-instructions" class="csl-entry" role="listitem">
<span>“Instructions for Form 990-PF (2022).”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/instructions/i990pf">https://www.irs.gov/instructions/i990pf</a>.
</div>
<div id="ref-activity-codes" class="csl-entry" role="listitem">
<span>“IRS Activity Codes.”</span> n.d. National Center for Charitable Statistics. <a href="https://nccs.urban.org/publication/irs-activity-codes">https://nccs.urban.org/publication/irs-activity-codes</a>.
</div>
<div id="ref-irs-private-foundations" class="csl-entry" role="listitem">
<span>“Private Foundations.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/charitable-organizations/private-foundations">https://www.irs.gov/charities-non-profits/charitable-organizations/private-foundations</a>.
</div>
<div id="ref-irs-private-op" class="csl-entry" role="listitem">
<span>“Private Operating Foundations.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/private-foundations/private-operating-foundations">https://www.irs.gov/charities-non-profits/private-foundations/private-operating-foundations</a>.
</div>
<div id="ref-irs-2014b" class="csl-entry" role="listitem">
Service, Internal Revenue. 2014. <span>“Form 1023-EZ: Streamlined Application for Recognition of Exemption Under Section 501(c)(3) of the Internal Revenue Code.”</span> Washington, DC. <a href="https://www.irs.gov/pub/irs-prior/f1023ez--2014.pdf">https://www.irs.gov/pub/irs-prior/f1023ez--2014.pdf</a>.
</div>
<div id="ref-irs-2020a" class="csl-entry" role="listitem">
———. 2020. <span>“Form 1023: Application for Recognition of Exemption Under Section 501(c)(3) of the Internal Revenue Code.”</span> Washington, DC. <a href="https://www.pay.gov/public/form/preview/pdf/104">https://www.pay.gov/public/form/preview/pdf/104</a>.
</div>
<div id="ref-irs-2022f" class="csl-entry" role="listitem">
———. 2022. <span>“Schedule a (Form 990): Public Charity Status and Public Support.”</span> Washington, DC. <a href="https://www.irs.gov/pub/irs-pdf/f990sa.pdf">https://www.irs.gov/pub/irs-pdf/f990sa.pdf</a>.
</div>
<div id="ref-irs-split-interest-trust-stats" class="csl-entry" role="listitem">
<span>“SOI Tax Stats - Split-Interest Trust Statistics.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/statistics/soi-tax-stats-split-interest-trust-statistics">https://www.irs.gov/statistics/soi-tax-stats-split-interest-trust-statistics</a>.
</div>
<div id="ref-irs-split-interest-trusts" class="csl-entry" role="listitem">
<span>“Split-Interest Trusts.”</span> n.d. Internal Revenue Service. <a href="https://www.irs.gov/charities-non-profits/private-foundations/split-interest-trusts">https://www.irs.gov/charities-non-profits/private-foundations/split-interest-trusts</a>.
</div>
</div>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p><span class="citation" data-cites="irs-exempt-purposes">(<a href="references.html#ref-irs-exempt-purposes" role="doc-biblioref"><span>“Exempt Purposes – Internal Revenue Code Section 501(c)(3),”</span> n.d.</a>)</span><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><span class="citation" data-cites="irs-def-of-exempt-op">(<a href="references.html#ref-irs-def-of-exempt-op" role="doc-biblioref"><span>“Definition of Exempt Operating Foundation,”</span> n.d.</a>)</span><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><span class="citation" data-cites="irs-990pf-instructions">(<a href="references.html#ref-irs-990pf-instructions" role="doc-biblioref"><span>“Instructions for Form 990-PF (2022),”</span> n.d.</a>)</span><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><span class="citation" data-cites="irs-private-op">(<a href="references.html#ref-irs-private-op" role="doc-biblioref"><span>“Private Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p><span class="citation" data-cites="irs-exempt-op">(<a href="references.html#ref-irs-exempt-op" role="doc-biblioref"><span>“Exempt Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p><span class="citation" data-cites="irs-disqualified">(<a href="references.html#ref-irs-disqualified" role="doc-biblioref"><span>“’Disqualified Individual’ – Exempt Operating Foundation,”</span> n.d.</a>)</span><a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p><span class="citation" data-cites="irs-grantmaking">(<a href="references.html#ref-irs-grantmaking" role="doc-biblioref"><span>“Grant-Making Foundations,”</span> n.d.</a>)</span><a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p><span class="citation" data-cites="irs-private-op">(<a href="references.html#ref-irs-private-op" role="doc-biblioref"><span>“Private Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p><span class="citation" data-cites="irs-exempt-op">(<a href="references.html#ref-irs-exempt-op" role="doc-biblioref"><span>“Exempt Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p><span class="citation" data-cites="irs-private-op">(<a href="references.html#ref-irs-private-op" role="doc-biblioref"><span>“Private Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p><span class="citation" data-cites="irs-exempt-op">(<a href="references.html#ref-irs-exempt-op" role="doc-biblioref"><span>“Exempt Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p><span class="citation" data-cites="irs-disqualified">(<a href="references.html#ref-irs-disqualified" role="doc-biblioref"><span>“’Disqualified Individual’ – Exempt Operating Foundation,”</span> n.d.</a>)</span><a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p><span class="citation" data-cites="irs-grantmaking">(<a href="references.html#ref-irs-grantmaking" role="doc-biblioref"><span>“Grant-Making Foundations,”</span> n.d.</a>)</span><a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p><span class="citation" data-cites="irs-private-op">(<a href="references.html#ref-irs-private-op" role="doc-biblioref"><span>“Private Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20"><p><span class="citation" data-cites="irs-exempt-op">(<a href="references.html#ref-irs-exempt-op" role="doc-biblioref"><span>“Exempt Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn21"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref21" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn22"><p><span class="citation" data-cites="irs-private-op">(<a href="references.html#ref-irs-private-op" role="doc-biblioref"><span>“Private Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref22" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn23"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref23" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn24"><p><span class="citation" data-cites="irs-exempt-op">(<a href="references.html#ref-irs-exempt-op" role="doc-biblioref"><span>“Exempt Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref24" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn25"><p><span class="citation" data-cites="irs-disqualified">(<a href="references.html#ref-irs-disqualified" role="doc-biblioref"><span>“’Disqualified Individual’ – Exempt Operating Foundation,”</span> n.d.</a>)</span><a href="#fnref25" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn26"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref26" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn27"><p><span class="citation" data-cites="irs-grantmaking">(<a href="references.html#ref-irs-grantmaking" role="doc-biblioref"><span>“Grant-Making Foundations,”</span> n.d.</a>)</span><a href="#fnref27" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn28"><p><span class="citation" data-cites="irs-private-op">(<a href="references.html#ref-irs-private-op" role="doc-biblioref"><span>“Private Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref28" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn29"><p><span class="citation" data-cites="irs-exempt-op">(<a href="references.html#ref-irs-exempt-op" role="doc-biblioref"><span>“Exempt Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref29" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn30"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref30" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn31"><p><span class="citation" data-cites="irs-private-op">(<a href="references.html#ref-irs-private-op" role="doc-biblioref"><span>“Private Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref31" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn32"><p><span class="citation" data-cites="irs-exempt-op">(<a href="references.html#ref-irs-exempt-op" role="doc-biblioref"><span>“Exempt Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref32" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn33"><p><span class="citation" data-cites="irs-disqualified">(<a href="references.html#ref-irs-disqualified" role="doc-biblioref"><span>“’Disqualified Individual’ – Exempt Operating Foundation,”</span> n.d.</a>)</span><a href="#fnref33" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn34"><p><span class="citation" data-cites="irs-grantmaking">(<a href="references.html#ref-irs-grantmaking" role="doc-biblioref"><span>“Grant-Making Foundations,”</span> n.d.</a>)</span><a href="#fnref34" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn35"><p><span class="citation" data-cites="irs-private-op">(<a href="references.html#ref-irs-private-op" role="doc-biblioref"><span>“Private Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref35" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn36"><p><span class="citation" data-cites="irs-exempt-op">(<a href="references.html#ref-irs-exempt-op" role="doc-biblioref"><span>“Exempt Operating Foundations,”</span> n.d.</a>)</span><a href="#fnref36" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn37"><p><span class="citation" data-cites="irs-instructions-8940">(<a href="references.html#ref-irs-instructions-8940" role="doc-biblioref"><span>“Instructions for Form 8940 (04/2023),”</span> n.d.</a>)</span><a href="#fnref37" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn38"><p><span class="citation" data-cites="irs-private-foundations">(<a href="references.html#ref-irs-private-foundations" role="doc-biblioref"><span>“Private Foundations,”</span> n.d.</a>)</span><a href="#fnref38" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn39"><p><span class="citation" data-cites="irs-who-must-file">(<a href="references.html#ref-irs-who-must-file" role="doc-biblioref"><span>“Annual Exempt Organization Return: Who Must File,”</span> n.d.</a>)</span><a href="#fnref39" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn40"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref40" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn41"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref41" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn42"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref42" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn43"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref43" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn44"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref44" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn45"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref45" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn46"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref46" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn47"><p><span class="citation" data-cites="activity-codes">(<a href="references.html#ref-activity-codes" role="doc-biblioref"><span>“IRS Activity Codes,”</span> n.d.</a>)</span><a href="#fnref47" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn48"><p><span class="citation" data-cites="irs-charitable-trusts">(<a href="references.html#ref-irs-charitable-trusts" role="doc-biblioref"><span>“Charitable Trusts,”</span> n.d.</a>)</span><a href="#fnref48" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn49"><p><span class="citation" data-cites="irs-charitable-trusts">(<a href="references.html#ref-irs-charitable-trusts" role="doc-biblioref"><span>“Charitable Trusts,”</span> n.d.</a>)</span><a href="#fnref49" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn50"><p><span class="citation" data-cites="irs-990pf-instructions">(<a href="references.html#ref-irs-990pf-instructions" role="doc-biblioref"><span>“Instructions for Form 990-PF (2022),”</span> n.d.</a>)</span><a href="#fnref50" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn51"><p><span class="citation" data-cites="irs-charitable-trusts">(<a href="references.html#ref-irs-charitable-trusts" role="doc-biblioref"><span>“Charitable Trusts,”</span> n.d.</a>)</span><a href="#fnref51" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn52"><p><span class="citation" data-cites="irs-charitable-trusts">(<a href="references.html#ref-irs-charitable-trusts" role="doc-biblioref"><span>“Charitable Trusts,”</span> n.d.</a>)</span><a href="#fnref52" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn53"><p><span class="citation" data-cites="irs-990ez-instructions irs-990-instructions">(<a href="references.html#ref-irs-990ez-instructions" role="doc-biblioref"><span>“Instructions for Form 990-EZ (2022),”</span> n.d.</a>; <a href="references.html#ref-irs-990-instructions" role="doc-biblioref"><span>“Instructions for Form 990 Return of Organization Exempt from Income Tax (2022),”</span> n.d.</a>)</span><a href="#fnref53" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn54"><p><span class="citation" data-cites="irs-split-interest-trust-stats">(<a href="references.html#ref-irs-split-interest-trust-stats" role="doc-biblioref"><span>“SOI Tax Stats - Split-Interest Trust Statistics,”</span> n.d.</a>)</span><a href="#fnref54" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn55"><p><span class="citation" data-cites="irs-form-5227">(<a href="references.html#ref-irs-form-5227" role="doc-biblioref"><span>“Instructions for Form 5227 (2022),”</span> n.d.</a>)</span><a href="#fnref55" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn56"><p><span class="citation" data-cites="irs-split-interest-trusts">(<a href="references.html#ref-irs-split-interest-trusts" role="doc-biblioref"><span>“Split-Interest Trusts,”</span> n.d.</a>)</span><a href="#fnref56" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn57"><p><span class="citation" data-cites="irs-form-5227">(<a href="references.html#ref-irs-form-5227" role="doc-biblioref"><span>“Instructions for Form 5227 (2022),”</span> n.d.</a>)</span><a href="#fnref57" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./standard-04.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>